/**
 * Extract data from Excel files into TypeScript source files.
 * Run with: npm run extract
 */
import XLSX from 'xlsx';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const DATA_DIR = join(import.meta.dirname, '..', 'src', 'data');
mkdirSync(DATA_DIR, { recursive: true });

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readWorkbook(name: string) {
  return XLSX.readFile(join(import.meta.dirname, '..', 'data', name));
}

/** Read a table that spans 5 columns starting at `startCol` (0-based). */
function readTable(
  ws: XLSX.WorkSheet,
  startCol: number,
): { name: string; entries: { name: string; source: string; weight: number }[] } | null {
  const range = XLSX.utils.decode_range(ws['!ref']!);
  const headerCell = ws[XLSX.utils.encode_cell({ r: 0, c: startCol })];
  if (!headerCell || !headerCell.v) return null;

  const name = String(headerCell.v);
  const entries: { name: string; source: string; weight: number }[] = [];

  for (let r = 1; r <= range.e.r; r++) {
    const nameCell = ws[XLSX.utils.encode_cell({ r, c: startCol })];
    const srcCell = ws[XLSX.utils.encode_cell({ r, c: startCol + 1 })];
    const weightCell = ws[XLSX.utils.encode_cell({ r, c: startCol + 2 })];
    if (!nameCell || !nameCell.v) continue;
    const weight = weightCell ? Number(weightCell.v) : 0;
    if (weight <= 0) continue;
    entries.push({
      name: String(nameCell.v).trim(),
      source: srcCell ? String(srcCell.v).trim() : '',
      weight,
    });
  }
  return { name, entries };
}

/** Read all tables on a sheet (spaced every `colStep` columns). */
function readAllTables(ws: XLSX.WorkSheet, colStep = 5) {
  const range = XLSX.utils.decode_range(ws['!ref']!);
  const tables: ReturnType<typeof readTable>[] = [];
  for (let c = 0; c <= range.e.c; c += colStep) {
    const t = readTable(ws, c);
    if (t && t.entries.length > 0) tables.push(t);
  }
  return tables.filter(Boolean) as NonNullable<ReturnType<typeof readTable>>[];
}

function writeTS(filename: string, varName: string, data: unknown, typeAnnotation?: string) {
  const json = JSON.stringify(data, null, 2);
  const annotation = typeAnnotation ? `: ${typeAnnotation}` : '';
  const content = `// Auto-generated by scripts/extract-data.ts — do not edit\n\nexport const ${varName}${annotation} = ${json} as const;\n`;
  writeFileSync(join(DATA_DIR, filename), content);
  console.log(`  wrote ${filename}`);
}

// ---------------------------------------------------------------------------
// Extract from Loot Tables.xlsx
// ---------------------------------------------------------------------------

const lootWB = readWorkbook('Loot Tables.xlsx');

// --- DMG Gems ---
console.log('Extracting DMG Gems...');
{
  const ws = lootWB.Sheets['DMG Gems'];
  const tables = readAllTables(ws);
  writeTS('gems-dmg.ts', 'DMG_GEMS', tables);
}

// --- DMG Art ---
console.log('Extracting DMG Art...');
{
  const ws = lootWB.Sheets['DMG Art'];
  const tables = readAllTables(ws);
  writeTS('art-dmg.ts', 'DMG_ART', tables);
}

// --- Custom Gems (New Gems) ---
console.log('Extracting Custom Gems...');
{
  const ws = lootWB.Sheets['New Gems'];
  const range = XLSX.utils.decode_range(ws['!ref']!);

  // Metadata in columns A-D (rows 1+)
  const gemMeta: { rarity: string; baseValue: number; tableName: string }[] = [];
  for (let r = 1; r <= range.e.r; r++) {
    const rarity = ws[XLSX.utils.encode_cell({ r, c: 0 })]?.v;
    const baseVal = ws[XLSX.utils.encode_cell({ r, c: 1 })]?.v;
    const tableName = ws[XLSX.utils.encode_cell({ r, c: 4 })]?.v;
    if (!rarity && !tableName) break;
    gemMeta.push({
      rarity: String(rarity || ''),
      baseValue: Number(baseVal || 0),
      tableName: String(tableName || ''),
    });
  }

  // Tables start at column F (index 5), every 5 columns
  // But the layout is: col5=baseVal, col6=tableName, col7=weight, col8=dieRange, col9=import
  // Actually the structure is irregular — let me read more carefully
  // Col E(4)=TableName header row, then col F(5) onward has base, name, weight, d100, import
  // The tables start at column 6 (G), stepping by 5: cols 6,11,16,21,26,31,36,41
  const gemTables: { name: string; baseValue: number; entries: { name: string; weight: number }[] }[] = [];
  for (let startC = 6; startC <= range.e.c; startC += 5) {
    const nameCell = ws[XLSX.utils.encode_cell({ r: 0, c: startC })];
    if (!nameCell?.v) continue;
    const tableName = String(nameCell.v);
    // Find the base value from the column before (startC - 1)
    const baseCell = ws[XLSX.utils.encode_cell({ r: 0, c: startC - 1 })];
    const baseValue = baseCell ? Number(baseCell.v) : 0;

    const entries: { name: string; weight: number }[] = [];
    for (let r = 1; r <= range.e.r; r++) {
      const entryName = ws[XLSX.utils.encode_cell({ r, c: startC })]?.v;
      const weight = ws[XLSX.utils.encode_cell({ r, c: startC + 1 })]?.v;
      if (!entryName) continue;
      const w = Number(weight || 0);
      if (w <= 0) continue;
      entries.push({ name: String(entryName).trim(), weight: w });
    }
    if (entries.length > 0) {
      gemTables.push({ name: tableName, baseValue, entries });
    }
  }
  writeTS('gems.ts', 'CUSTOM_GEMS', gemTables);
  writeTS('gem-meta.ts', 'GEM_META', gemMeta);
}

// --- Custom Art (New Art) ---
console.log('Extracting Custom Art...');
{
  const ws = lootWB.Sheets['New Art'];
  const range = XLSX.utils.decode_range(ws['!ref']!);

  const artMeta: { rarity: string; baseValue: number; tableName: string }[] = [];
  for (let r = 1; r <= range.e.r; r++) {
    const rarity = ws[XLSX.utils.encode_cell({ r, c: 0 })]?.v;
    const baseVal = ws[XLSX.utils.encode_cell({ r, c: 1 })]?.v;
    const tableName = ws[XLSX.utils.encode_cell({ r, c: 4 })]?.v;
    if (!rarity && !tableName) break;
    artMeta.push({
      rarity: String(rarity || ''),
      baseValue: Number(baseVal || 0),
      tableName: String(tableName || ''),
    });
  }

  const artTables: { name: string; baseValue: number; entries: { name: string; weight: number }[] }[] = [];
  for (let startC = 6; startC <= range.e.c; startC += 5) {
    const nameCell = ws[XLSX.utils.encode_cell({ r: 0, c: startC })];
    if (!nameCell?.v) continue;
    const tableName = String(nameCell.v);
    const baseCell = ws[XLSX.utils.encode_cell({ r: 0, c: startC - 1 })];
    const baseValue = baseCell ? Number(baseCell.v) : 0;

    const entries: { name: string; weight: number }[] = [];
    for (let r = 1; r <= range.e.r; r++) {
      const entryName = ws[XLSX.utils.encode_cell({ r, c: startC })]?.v;
      const weight = ws[XLSX.utils.encode_cell({ r, c: startC + 1 })]?.v;
      if (!entryName) continue;
      const w = Number(weight || 0);
      if (w <= 0) continue;
      entries.push({ name: String(entryName).trim(), weight: w });
    }
    if (entries.length > 0) {
      artTables.push({ name: tableName, baseValue, entries });
    }
  }
  writeTS('art.ts', 'CUSTOM_ART', artTables);
  writeTS('art-meta.ts', 'ART_META', artMeta);
}

// --- DMG Treasure Hoards (reference only) ---
console.log('Extracting DMG Treasure Hoards...');
{
  const ws = lootWB.Sheets['DMG Treasure Hoards'];
  const range = XLSX.utils.decode_range(ws['!ref']!);

  const hoards: { tier: string; baseCoins: string; entries: { result: string; weight: number }[] }[] = [];
  for (let startC = 0; startC <= range.e.c; startC += 5) {
    const nameCell = ws[XLSX.utils.encode_cell({ r: 0, c: startC })];
    if (!nameCell?.v) continue;
    const tier = String(nameCell.v);

    // Row 1 has base coins
    const coinsCell = ws[XLSX.utils.encode_cell({ r: 1, c: startC })];
    const baseCoins = coinsCell ? String(coinsCell.v) : '';

    const entries: { result: string; weight: number }[] = [];
    for (let r = 2; r <= range.e.r; r++) {
      const resultCell = ws[XLSX.utils.encode_cell({ r, c: startC })];
      const weightCell = ws[XLSX.utils.encode_cell({ r, c: startC + 1 })];
      if (!resultCell?.v) continue;
      const w = weightCell ? Number(weightCell.v) : 0;
      if (w <= 0) continue;
      entries.push({ result: String(resultCell.v).trim(), weight: w });
    }
    hoards.push({ tier, baseCoins, entries });
  }
  writeTS('hoards-dmg.ts', 'DMG_HOARDS', hoards);
}

// --- DMG Individual Treasure (reference only) ---
console.log('Extracting DMG Individual Treasure...');
{
  const ws = lootWB.Sheets['DMG Individual Treasure'];
  const range = XLSX.utils.decode_range(ws['!ref']!);

  const tables: { tier: string; entries: { result: string; weight: number }[] }[] = [];
  for (let startC = 0; startC <= range.e.c; startC += 5) {
    const nameCell = ws[XLSX.utils.encode_cell({ r: 0, c: startC })];
    if (!nameCell?.v) continue;

    const entries: { result: string; weight: number }[] = [];
    for (let r = 1; r <= range.e.r; r++) {
      const resultCell = ws[XLSX.utils.encode_cell({ r, c: startC })];
      const weightCell = ws[XLSX.utils.encode_cell({ r, c: startC + 2 })];
      if (!resultCell?.v) continue;
      const w = weightCell ? Number(weightCell.v) : 0;
      if (w <= 0) continue;
      entries.push({ result: String(resultCell.v).trim(), weight: w });
    }
    tables.push({ tier: String(nameCell.v), entries });
  }
  writeTS('individual-dmg.ts', 'DMG_INDIVIDUAL', tables);
}

// ---------------------------------------------------------------------------
// Extract from Item Tables.xlsx
// ---------------------------------------------------------------------------

const itemWB = readWorkbook('Item Tables.xlsx');

// --- Magic Item Tables (all expanded sheets) ---
console.log('Extracting Magic Item Tables...');
{
  const sheetNames = [
    'DMG Magic Item Tables',
    'Table A Common',
    'Table B Minor Uncommon',
    'Table F Major Uncommon',
    'Table C Minor Rare',
    'Table G Major Rare',
    'Table D Minor Very Rare',
    'Table H Major Very Rare',
    'Table E Minor Legendary',
    'Table I Major Legendary',
  ];

  const allTables: Record<string, { name: string; source: string; weight: number }[]> = {};

  for (const sheetName of sheetNames) {
    const ws = itemWB.Sheets[sheetName];
    if (!ws) { console.warn(`  sheet "${sheetName}" not found, skipping`); continue; }
    const tables = readAllTables(ws);
    for (const t of tables) {
      allTables[t.name] = t.entries;
    }
  }
  writeTS('magic-items.ts', 'MAGIC_ITEMS', allTables);
}

// --- Spells ---
console.log('Extracting Spells...');
{
  const ws = itemWB.Sheets['All Spells'];
  const tables = readAllTables(ws);
  writeTS('spells.ts', 'SPELL_TABLES', tables);
}

// --- Supplemental Types ---
console.log('Extracting Supplemental Types...');
{
  const ws = itemWB.Sheets['Supplemental Types'];
  // This sheet has a Table-of-Contents in col A, then tables starting at col B
  // Tables are spaced every 5 cols but start at col 1 (B)
  const range = XLSX.utils.decode_range(ws['!ref']!);
  const tables: { name: string; entries: { name: string; source: string; weight: number }[] }[] = [];

  for (let c = 1; c <= range.e.c; c += 5) {
    const t = readTable(ws, c);
    if (t && t.entries.length > 0) tables.push(t);
  }
  writeTS('supplemental.ts', 'SUPPLEMENTAL_TABLES', tables);
}

// --- Sourcebooks ---
console.log('Extracting Sourcebooks...');
{
  const ws = itemWB.Sheets['Cover Sheet'];
  const range = XLSX.utils.decode_range(ws['!ref']!);
  const sourcebooks: { name: string; acronym: string }[] = [];

  // Sourcebook list starts at row 12 (0-indexed=11), columns A-B
  for (let r = 11; r <= range.e.r; r++) {
    const nameCell = ws[XLSX.utils.encode_cell({ r, c: 0 })];
    const acroCell = ws[XLSX.utils.encode_cell({ r, c: 1 })];
    if (!nameCell?.v || !acroCell?.v) continue;
    const name = String(nameCell.v).trim();
    const acronym = String(acroCell.v).trim();
    if (name && acronym && acronym.length <= 6) {
      sourcebooks.push({ name, acronym });
    }
  }
  writeTS('sourcebooks.ts', 'SOURCEBOOKS', sourcebooks);
}

console.log('\nDone! All data extracted to src/data/');
