// Auto-generated by scripts/extract-data.ts — do not edit

export const ART_META = [
  {
    "rarity": "Common",
    "baseValue": 20,
    "tableName": "Art-1-100-gp"
  },
  {
    "rarity": "Uncommon",
    "baseValue": 100,
    "tableName": "Art-2-500-gp"
  },
  {
    "rarity": "Uncommon",
    "baseValue": 250,
    "tableName": "Art-3-1250-gp"
  },
  {
    "rarity": "Rare",
    "baseValue": 1000,
    "tableName": "Art-4-5000-gp"
  },
  {
    "rarity": "Rare",
    "baseValue": 2500,
    "tableName": "Art-5-12500-gp"
  },
  {
    "rarity": "Very Rare",
    "baseValue": 10000,
    "tableName": "Art-6-50000-gp"
  },
  {
    "rarity": "Very Rare",
    "baseValue": 25000,
    "tableName": "Art-7-125000-gp"
  },
  {
    "rarity": "Legendary",
    "baseValue": 100000,
    "tableName": "Art-8-500000-gp"
  }
];
