// Auto-generated by scripts/extract-data.ts — do not edit

export const DMG_ART = [
  {
    "name": "Art-25gp",
    "entries": [
      {
        "name": "Silver ewer",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Carved bone statuette",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Small gold bracelet",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Cloth-of-gold vestments",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Black velvet mask stitched with silver thread",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Copper chalice with silver filigree",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Pair of engraved bone dice",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Small mirror set in a painted wooden frame",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Embroidered silk handkerchief",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Gold locket with a painted portrait inside",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Art-250gp",
    "entries": [
      {
        "name": "Gold ring set with bloodstones",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Carved ivory statuette",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Large gold bracelet",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Silver necklace with a gemstone pendant",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Bronze crown",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Silk robe with gold embroidery",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Large well-made tapestry",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Brass mug with jade inlay",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Box of turquoise animal figurines",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Gold bird cage with electrum filigree",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Art-750gp",
    "entries": [
      {
        "name": "Silver chalice set with moonstones",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Silver-plated steel longsword with jet set in hilt",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Carved harp of exotic wood with ivory inlay and zircon gems",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Small gold idol",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Gold dragon comb set with red garnets as eyes",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Bottle stopper cork embossed with gold leaf and set with amethysts",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Ceremonial electrum dagger with a black pearl in the pommel",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Silver and gold brooch",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Obsidian statuette with gold fittings and inlay",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Painted gold war mask",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Art-2500gp",
    "entries": [
      {
        "name": "Fine gold chain set with a fire opal",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Old masterpiece painting",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Embroidered silk and velvet mantle set with numerous moonstones",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Platinum bracelet set with a sapphire",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Embroidered glove set with jewel chips",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Jeweled anklet",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Gold music box",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Gold circlet set with four aquamarines",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Eye patch with a mock eye set in blue sapphire and moonstone",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "A necklace string of small pink pearls",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Art-7500gp",
    "entries": [
      {
        "name": "Jeweled gold crown",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Jeweled platinum ring",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Small gold statuette set with rubies",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Gold cup set with emeralds",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Gold jewelry box with platinum filigree",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Painted gold child's sarcophagus",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Jade game board with solid gold playing pieces",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Bejeweled ivory drinking horn with gold filigree",
        "source": "DMG",
        "weight": 1
      }
    ]
  }
];
