// Auto-generated by scripts/extract-data.ts — do not edit

export const CUSTOM_ART = [
  {
    "name": "Art-1-100-gp",
    "baseValue": 20,
    "entries": [
      {
        "name": "Bejeweled",
        "weight": 20
      },
      {
        "name": "Large Bejeweled",
        "weight": 5
      },
      {
        "name": "Ceramic",
        "weight": 8
      },
      {
        "name": "Large Ceramic",
        "weight": 2
      },
      {
        "name": "Fabric",
        "weight": 12
      },
      {
        "name": "Large Fabric",
        "weight": 3
      },
      {
        "name": "Glass",
        "weight": 8
      },
      {
        "name": "Large Glass",
        "weight": 2
      },
      {
        "name": "Painted",
        "weight": 10
      },
      {
        "name": "Large Painted",
        "weight": 5
      },
      {
        "name": "Wooden",
        "weight": 6
      },
      {
        "name": "Large Wooden",
        "weight": 4
      },
      {
        "name": "Written",
        "weight": 12
      },
      {
        "name": "Large Written",
        "weight": 3
      }
    ]
  },
  {
    "name": "Art-2-500-gp",
    "baseValue": 100,
    "entries": [
      {
        "name": "Bejeweled",
        "weight": 20
      },
      {
        "name": "Large Bejeweled",
        "weight": 5
      },
      {
        "name": "Ceramic",
        "weight": 8
      },
      {
        "name": "Large Ceramic",
        "weight": 2
      },
      {
        "name": "Fabric",
        "weight": 12
      },
      {
        "name": "Large Fabric",
        "weight": 3
      },
      {
        "name": "Glass",
        "weight": 8
      },
      {
        "name": "Large Glass",
        "weight": 2
      },
      {
        "name": "Painted",
        "weight": 10
      },
      {
        "name": "Large Painted",
        "weight": 5
      },
      {
        "name": "Wooden",
        "weight": 6
      },
      {
        "name": "Large Wooden",
        "weight": 4
      },
      {
        "name": "Written",
        "weight": 12
      },
      {
        "name": "Large Written",
        "weight": 3
      }
    ]
  },
  {
    "name": "Art-3-1250-gp",
    "baseValue": 250,
    "entries": [
      {
        "name": "Bejeweled",
        "weight": 20
      },
      {
        "name": "Large Bejeweled",
        "weight": 5
      },
      {
        "name": "Ceramic",
        "weight": 8
      },
      {
        "name": "Large Ceramic",
        "weight": 2
      },
      {
        "name": "Fabric",
        "weight": 12
      },
      {
        "name": "Large Fabric",
        "weight": 3
      },
      {
        "name": "Glass",
        "weight": 8
      },
      {
        "name": "Large Glass",
        "weight": 2
      },
      {
        "name": "Painted",
        "weight": 10
      },
      {
        "name": "Large Painted",
        "weight": 5
      },
      {
        "name": "Wooden",
        "weight": 6
      },
      {
        "name": "Large Wooden",
        "weight": 4
      },
      {
        "name": "Written",
        "weight": 12
      },
      {
        "name": "Large Written",
        "weight": 3
      }
    ]
  },
  {
    "name": "Art-4-5000-gp",
    "baseValue": 1000,
    "entries": [
      {
        "name": "Bejeweled",
        "weight": 20
      },
      {
        "name": "Large Bejeweled",
        "weight": 5
      },
      {
        "name": "Ceramic",
        "weight": 8
      },
      {
        "name": "Large Ceramic",
        "weight": 2
      },
      {
        "name": "Fabric",
        "weight": 12
      },
      {
        "name": "Large Fabric",
        "weight": 3
      },
      {
        "name": "Glass",
        "weight": 8
      },
      {
        "name": "Large Glass",
        "weight": 2
      },
      {
        "name": "Painted",
        "weight": 10
      },
      {
        "name": "Large Painted",
        "weight": 5
      },
      {
        "name": "Wooden",
        "weight": 6
      },
      {
        "name": "Large Wooden",
        "weight": 4
      },
      {
        "name": "Written",
        "weight": 12
      },
      {
        "name": "Large Written",
        "weight": 3
      }
    ]
  },
  {
    "name": "Art-5-12500-gp",
    "baseValue": 2500,
    "entries": [
      {
        "name": "Bejeweled",
        "weight": 20
      },
      {
        "name": "Large Bejeweled",
        "weight": 5
      },
      {
        "name": "Ceramic",
        "weight": 8
      },
      {
        "name": "Large Ceramic",
        "weight": 2
      },
      {
        "name": "Fabric",
        "weight": 12
      },
      {
        "name": "Large Fabric",
        "weight": 3
      },
      {
        "name": "Glass",
        "weight": 8
      },
      {
        "name": "Large Glass",
        "weight": 2
      },
      {
        "name": "Painted",
        "weight": 10
      },
      {
        "name": "Large Painted",
        "weight": 5
      },
      {
        "name": "Wooden",
        "weight": 6
      },
      {
        "name": "Large Wooden",
        "weight": 4
      },
      {
        "name": "Written",
        "weight": 12
      },
      {
        "name": "Large Written",
        "weight": 3
      }
    ]
  },
  {
    "name": "Art-6-50000-gp",
    "baseValue": 10000,
    "entries": [
      {
        "name": "Bejeweled",
        "weight": 20
      },
      {
        "name": "Large Bejeweled",
        "weight": 5
      },
      {
        "name": "Ceramic",
        "weight": 8
      },
      {
        "name": "Large Ceramic",
        "weight": 2
      },
      {
        "name": "Fabric",
        "weight": 12
      },
      {
        "name": "Large Fabric",
        "weight": 3
      },
      {
        "name": "Glass",
        "weight": 8
      },
      {
        "name": "Large Glass",
        "weight": 2
      },
      {
        "name": "Painted",
        "weight": 10
      },
      {
        "name": "Large Painted",
        "weight": 5
      },
      {
        "name": "Wooden",
        "weight": 6
      },
      {
        "name": "Large Wooden",
        "weight": 4
      },
      {
        "name": "Written",
        "weight": 12
      },
      {
        "name": "Large Written",
        "weight": 3
      }
    ]
  }
];
