// Auto-generated by scripts/extract-data.ts — do not edit

export const GEM_META = [
  {
    "rarity": "Common",
    "baseValue": 5,
    "tableName": "Gems-1-25-gp"
  },
  {
    "rarity": "Uncommon",
    "baseValue": 10,
    "tableName": "Gems-2-50-gp"
  },
  {
    "rarity": "Uncommon",
    "baseValue": 25,
    "tableName": "Gems-3-125-gp"
  },
  {
    "rarity": "Rare",
    "baseValue": 100,
    "tableName": "Gems-4-500-gp"
  },
  {
    "rarity": "Rare",
    "baseValue": 250,
    "tableName": "Gems-5-1250-gp"
  },
  {
    "rarity": "Very Rare",
    "baseValue": 1000,
    "tableName": "Gems-6-5000-gp"
  },
  {
    "rarity": "Very Rare",
    "baseValue": 2500,
    "tableName": "Gems-7-12500-gp"
  },
  {
    "rarity": "Legendary",
    "baseValue": 10000,
    "tableName": "Gems-8-50000-gp"
  }
];
