// Auto-generated by scripts/extract-data.ts — do not edit

export const DMG_GEMS = [
  {
    "name": "Gems-10gp",
    "entries": [
      {
        "name": "Azurite (opaque mottled deep blue)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Banded agate (translucent striped brown, blue, white, or red)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Blue quartz (transparent pale blue)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Eye agate (translucent circles of gray, white, brown, blue, or green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Hematite (opaque gray-black)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Lapis lazuli (opaque light and dark blue with yellow flecks)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Malachite (opaque striated light and dark green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Moss agate (translucent pink or yellow-white with mossy gray or green markings)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Obsidian (opaque black)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Rhodochrosite (opaque light pink)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Tiger eye (translucent brown with golden center)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Turquoise (opaque light blue-green)",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Gems-50gp",
    "entries": [
      {
        "name": "Bloodstone (opaque dark gray with red flecks)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Carnelian (opaque orange to red-brown)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Chalcedony (opaque white)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Chrysoprase (translucent green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Citrine (transparent pale yellow-brown)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Jasper (opaque blue, black, or brown)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Moonstone (translucent white with pale blue glow)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Onyx (opaque bands of black and white, or pure black or white)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Quartz (transparent white, smoky gray, or yellow)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Sardonyx (opaque bands of red and white)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Star rose quartz (translucent rosy stone with white star-shaped center)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Zircon (transparent pale blue-green)",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Gems-100gp",
    "entries": [
      {
        "name": "Amber (transparent watery gold to rich gold)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Amethyst (transparent deep purple)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Chrysoberyl (transparent yellow-green to pale green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Coral (opaque crimson)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Garnet (transparent red, brown-green, or violet)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Jade (translucent light green, deep green, or white)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Jet (opaque deep black)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Pearl (opaque lustrous white, yellow, or pink)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Spinel (transparent red, red-brown, or deep green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Tourmaline (transparent pale green, blue, brown, or red)",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Gems-500gp",
    "entries": [
      {
        "name": "Alexandrite (transparent dark green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Aquamarine (transparent pale blue-green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Black pearl (opaque pure black)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Blue spinel (transparent deep blue)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Peridot (transparent rich olive green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Topaz (transparent golden yellow)",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Gems-1000gp",
    "entries": [
      {
        "name": "Black opal (translucent dark green with black mottling and golden flecks)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Blue sapphire (transparent blue-white to medium blue)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Emerald (transparent deep bright green)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Fire opal (translucent fiery red)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Opal (translucent pale blue with green and golden mottling)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Star ruby (translucent ruby with white star-shaped center)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Star sapphire (translucent blue sapphire with white star-shaped center)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Yellow sapphire (transparent fiery yellow or yellow-green)",
        "source": "DMG",
        "weight": 1
      }
    ]
  },
  {
    "name": "Gems-5000gp",
    "entries": [
      {
        "name": "Black sapphire (translucent lustrous black with glowing highlights)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Diamond (transparent blue-white, canary, pink, brown, or blue)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Jacinth (transparent fiery orange)",
        "source": "DMG",
        "weight": 1
      },
      {
        "name": "Ruby (transparent clear red to deep crimson)",
        "source": "DMG",
        "weight": 1
      }
    ]
  }
];
