// Auto-generated by scripts/extract-data.ts — do not edit

export const CUSTOM_GEMS = [
  {
    "name": "Gems-1-25-gp",
    "baseValue": 5,
    "entries": [
      {
        "name": "Agate",
        "weight": 4
      },
      {
        "name": "Amethyst",
        "weight": 4
      },
      {
        "name": "Aquamarine",
        "weight": 4
      },
      {
        "name": "Citrine",
        "weight": 4
      },
      {
        "name": "Diamond",
        "weight": 24
      },
      {
        "name": "Emerald",
        "weight": 4
      },
      {
        "name": "Garnet",
        "weight": 4
      },
      {
        "name": "Jade",
        "weight": 10
      },
      {
        "name": "Jet",
        "weight": 3
      },
      {
        "name": "Onyx",
        "weight": 4
      },
      {
        "name": "Opal",
        "weight": 4
      },
      {
        "name": "Pearl",
        "weight": 4
      },
      {
        "name": "Peridot",
        "weight": 4
      },
      {
        "name": "Quartz",
        "weight": 3
      },
      {
        "name": "Ruby",
        "weight": 4
      },
      {
        "name": "Sapphire",
        "weight": 4
      },
      {
        "name": "Spinel",
        "weight": 4
      },
      {
        "name": "Topaz",
        "weight": 4
      },
      {
        "name": "Tourmaline",
        "weight": 4
      }
    ]
  },
  {
    "name": "Gems-2-50-gp",
    "baseValue": 10,
    "entries": [
      {
        "name": "Agate",
        "weight": 4
      },
      {
        "name": "Amethyst",
        "weight": 4
      },
      {
        "name": "Aquamarine",
        "weight": 4
      },
      {
        "name": "Citrine",
        "weight": 4
      },
      {
        "name": "Diamond",
        "weight": 20
      },
      {
        "name": "Emerald",
        "weight": 4
      },
      {
        "name": "Garnet",
        "weight": 4
      },
      {
        "name": "Jade",
        "weight": 10
      },
      {
        "name": "Jet",
        "weight": 3
      },
      {
        "name": "Onyx",
        "weight": 3
      },
      {
        "name": "Opal",
        "weight": 4
      },
      {
        "name": "Pearl",
        "weight": 4
      },
      {
        "name": "Peridot",
        "weight": 3
      },
      {
        "name": "Quartz",
        "weight": 3
      },
      {
        "name": "Ruby",
        "weight": 10
      },
      {
        "name": "Sapphire",
        "weight": 4
      },
      {
        "name": "Spinel",
        "weight": 4
      },
      {
        "name": "Topaz",
        "weight": 4
      },
      {
        "name": "Tourmaline",
        "weight": 4
      }
    ]
  },
  {
    "name": "Gems-3-125-gp",
    "baseValue": 25,
    "entries": [
      {
        "name": "Agate",
        "weight": 4
      },
      {
        "name": "Amethyst",
        "weight": 5
      },
      {
        "name": "Aquamarine",
        "weight": 4
      },
      {
        "name": "Citrine",
        "weight": 3
      },
      {
        "name": "Diamond",
        "weight": 4
      },
      {
        "name": "Emerald",
        "weight": 5
      },
      {
        "name": "Garnet",
        "weight": 4
      },
      {
        "name": "Jade",
        "weight": 4
      },
      {
        "name": "Onyx",
        "weight": 10
      },
      {
        "name": "Opal",
        "weight": 4
      },
      {
        "name": "Pearl",
        "weight": 25
      },
      {
        "name": "Peridot",
        "weight": 3
      },
      {
        "name": "Quartz",
        "weight": 3
      },
      {
        "name": "Ruby",
        "weight": 5
      },
      {
        "name": "Sapphire",
        "weight": 5
      },
      {
        "name": "Spinel",
        "weight": 4
      },
      {
        "name": "Topaz",
        "weight": 5
      },
      {
        "name": "Tourmaline",
        "weight": 3
      }
    ]
  },
  {
    "name": "Gems-4-500-gp",
    "baseValue": 100,
    "entries": [
      {
        "name": "Agate",
        "weight": 2
      },
      {
        "name": "Amethyst",
        "weight": 5
      },
      {
        "name": "Aquamarine",
        "weight": 4
      },
      {
        "name": "Citrine",
        "weight": 3
      },
      {
        "name": "Diamond",
        "weight": 25
      },
      {
        "name": "Emerald",
        "weight": 5
      },
      {
        "name": "Garnet",
        "weight": 3
      },
      {
        "name": "Jade",
        "weight": 3
      },
      {
        "name": "Onyx",
        "weight": 2
      },
      {
        "name": "Opal",
        "weight": 3
      },
      {
        "name": "Black Pearl",
        "weight": 15
      },
      {
        "name": "Peridot",
        "weight": 2
      },
      {
        "name": "Quartz",
        "weight": 2
      },
      {
        "name": "Ruby",
        "weight": 10
      },
      {
        "name": "Sapphire",
        "weight": 5
      },
      {
        "name": "Spinel",
        "weight": 3
      },
      {
        "name": "Topaz",
        "weight": 5
      },
      {
        "name": "Tourmaline",
        "weight": 3
      }
    ]
  },
  {
    "name": "Gems-5-1250-gp",
    "baseValue": 250,
    "entries": [
      {
        "name": "Agate",
        "weight": 15
      },
      {
        "name": "Amethyst",
        "weight": 3
      },
      {
        "name": "Aquamarine",
        "weight": 3
      },
      {
        "name": "Citrine",
        "weight": 2
      },
      {
        "name": "Diamond",
        "weight": 25
      },
      {
        "name": "Emerald",
        "weight": 3
      },
      {
        "name": "Jacinth",
        "weight": 10
      },
      {
        "name": "Jade",
        "weight": 2
      },
      {
        "name": "Black Pearl",
        "weight": 2
      },
      {
        "name": "Ruby",
        "weight": 15
      },
      {
        "name": "Sapphire",
        "weight": 15
      },
      {
        "name": "Spinel",
        "weight": 2
      },
      {
        "name": "Topaz",
        "weight": 3
      }
    ]
  },
  {
    "name": "Gems-6-5000-gp",
    "baseValue": 1000,
    "entries": [
      {
        "name": "Agate",
        "weight": 3
      },
      {
        "name": "Amethyst",
        "weight": 5
      },
      {
        "name": "Aquamarine",
        "weight": 4
      },
      {
        "name": "Citrine",
        "weight": 4
      },
      {
        "name": "Diamond",
        "weight": 25
      },
      {
        "name": "Emerald",
        "weight": 10
      },
      {
        "name": "Garnet",
        "weight": 3
      },
      {
        "name": "Jade",
        "weight": 4
      },
      {
        "name": "Opal",
        "weight": 4
      },
      {
        "name": "Peridot",
        "weight": 3
      },
      {
        "name": "Ruby",
        "weight": 10
      },
      {
        "name": "Sapphire",
        "weight": 10
      },
      {
        "name": "Spinel",
        "weight": 4
      },
      {
        "name": "Topaz",
        "weight": 5
      },
      {
        "name": "Tourmaline",
        "weight": 4
      }
    ]
  },
  {
    "name": "Gems-7-12500-gp",
    "baseValue": 2500,
    "entries": [
      {
        "name": "Agate",
        "weight": 1
      },
      {
        "name": "Amethyst",
        "weight": 1
      },
      {
        "name": "Aquamarine",
        "weight": 1
      },
      {
        "name": "Citrine",
        "weight": 1
      },
      {
        "name": "Diamond",
        "weight": 2
      },
      {
        "name": "Emerald",
        "weight": 1
      },
      {
        "name": "Garnet",
        "weight": 1
      },
      {
        "name": "Jacinth",
        "weight": 1
      },
      {
        "name": "Jade",
        "weight": 1
      },
      {
        "name": "Jet",
        "weight": 1
      },
      {
        "name": "Onyx",
        "weight": 1
      },
      {
        "name": "Opal",
        "weight": 1
      },
      {
        "name": "Peridot",
        "weight": 1
      },
      {
        "name": "Quartz",
        "weight": 1
      },
      {
        "name": "Ruby",
        "weight": 1
      },
      {
        "name": "Sapphire",
        "weight": 1
      },
      {
        "name": "Spinel",
        "weight": 1
      },
      {
        "name": "Topaz",
        "weight": 1
      },
      {
        "name": "Tourmaline",
        "weight": 1
      }
    ]
  },
  {
    "name": "Gems-8-50000-gp",
    "baseValue": 10000,
    "entries": [
      {
        "name": "Agate",
        "weight": 1
      },
      {
        "name": "Amethyst",
        "weight": 1
      },
      {
        "name": "Aquamarine",
        "weight": 1
      },
      {
        "name": "Citrine",
        "weight": 1
      },
      {
        "name": "Diamond",
        "weight": 2
      },
      {
        "name": "Emerald",
        "weight": 1
      },
      {
        "name": "Garnet",
        "weight": 1
      },
      {
        "name": "Jacinth",
        "weight": 1
      },
      {
        "name": "Jade",
        "weight": 1
      },
      {
        "name": "Jet",
        "weight": 1
      },
      {
        "name": "Onyx",
        "weight": 1
      },
      {
        "name": "Opal",
        "weight": 1
      },
      {
        "name": "Peridot",
        "weight": 1
      },
      {
        "name": "Quartz",
        "weight": 1
      },
      {
        "name": "Ruby",
        "weight": 1
      },
      {
        "name": "Sapphire",
        "weight": 1
      },
      {
        "name": "Spinel",
        "weight": 1
      },
      {
        "name": "Topaz",
        "weight": 1
      },
      {
        "name": "Tourmaline",
        "weight": 1
      }
    ]
  }
];
