// Auto-generated by scripts/extract-data.ts — do not edit

export const DMG_HOARDS = [
  {
    "tier": "Treasure Hoard: Challenge 0-4",
    "baseCoins": "[[6d6*100]] cp & [[3d6*100]] sp & [[2d6*10]] gp",
    "entries": [
      {
        "result": "Nothing",
        "weight": null
      },
      {
        "result": "[[2d6]] 10 gp gems",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects",
        "weight": null
      },
      {
        "result": "[[2d6]] 50 gp gems",
        "weight": null
      },
      {
        "result": "[[2d6]] 10 gp gems & [[1d6]] Magic Item Table A",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d6]] Magic Item Table A",
        "weight": null
      },
      {
        "result": "[[2d6]] 50 gp gems & [[1d6]] Magic Item Table A",
        "weight": null
      },
      {
        "result": "[[2d6]] 10 gp gems & [[1d4]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d4]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[2d6]] 50 gp gems & [[1d4]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[2d6]] 10 gp gems & [[1d4]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d4]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[2d6]] 50 gp gems & [[1d4]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d4]] Magic Item Table F",
        "weight": null
      },
      {
        "result": "[[2d6]] 50 gp gems & [[1d4]] Magic Item Table F",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & 1 Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[2d6]] 50 gp gems & 1 Magic Item Table G",
        "weight": null
      }
    ]
  },
  {
    "tier": "Treasure Hoard: Challenge 5-10",
    "baseCoins": "[[2d6*100]] cp & [[2d6*1000]] sp & [[6d6*100]] gp & [[3d6*10]] pp",
    "entries": [
      {
        "result": "Nothing",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects",
        "weight": null
      },
      {
        "result": "[[3d6]] 50 gp gems",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d6]] Magic Item Table A",
        "weight": null
      },
      {
        "result": "[[3d6]] 50 gp gems & [[1d6]] Magic Item Table A",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems & [[1d6]] Magic Item Table A",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d6]] Magic Item Table A",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d4]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[3d6]] 50 gp gems & [[1d4]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems & [[1d4]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d4]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d4]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[3d6]] 50 gp gems & [[1d4]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems & [[1d4]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d4]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & 1 Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[3d6]] 50 gp gems & 1 Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems & 1 Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & 1 Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[2d4]] 25 gp art objects & [[1d4]] Magic Item Table F",
        "weight": null
      },
      {
        "result": "[[3d6]] 50 gp gems & [[1d4]] Magic Item Table F",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems & [[1d4]] Magic Item Table F",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d4]] Magic Item Table F",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[3d6]] 100 gp gems & 1 Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & 1 Magic Item Table H",
        "weight": null
      }
    ]
  },
  {
    "tier": "Treasure Hoard: Challenge 11-16",
    "baseCoins": "[[4d6*1000]] gp & [[5d6*100]] pp",
    "entries": [
      {
        "result": "Nothing",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d4]] Magic Item Table A & [[1d6]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects & [[1d4]] Magic Item Table A & [[1d6]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems & [[1d4]] Magic Item Table A & [[1d6]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d4]] Magic Item Table A & [[1d6]] Magic Item Table B",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d6]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects & [[1d6]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems & [[1d6]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d6]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d4]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects & [[1d4]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems & [[1d4]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d4]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & 1 Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects & 1 Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems & 1 Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & 1 Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & 1 Magic Item Table F & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects & 1 Magic Item Table F & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems & 1 Magic Item Table F & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & 1 Magic Item Table F & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[2d4]] 250 gp art objects & 1 Magic Item Table I",
        "weight": null
      },
      {
        "result": "[[2d4]] 750 gp art objects & 1 Magic Item Table I",
        "weight": null
      },
      {
        "result": "[[3d6]] 500 gp gems & 1 Magic Item Table I",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & 1 Magic Item Table I",
        "weight": null
      }
    ]
  },
  {
    "tier": "Treasure Hoard: Challenge 11-16",
    "baseCoins": "[[12d6*1000]] gp & [[8d6*1000]] pp",
    "entries": [
      {
        "result": "Nothing",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d8]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[1d10]] 2500 gp art objects & [[1d8]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[1d4]] 7500 gp art objects & [[1d8]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[1d8]] 5000 gp gems & [[1d8]] Magic Item Table C",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d6]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[1d10]] 2500 gp art objects & [[1d6]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[1d4]] 7500 gp art objects & [[1d6]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[1d8]] 5000 gp gems & [[1d6]] Magic Item Table D",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d6]] Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[1d10]] 2500 gp art objects & [[1d6]] Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[1d4]] 7500 gp art objects & [[1d6]] Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[1d8]] 5000 gp gems & [[1d6]] Magic Item Table E",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[1d10]] 2500 gp art objects & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[1d4]] 7500 gp art objects & [[1d4]] Magic Item Table G",
        "weight": null
      },
      {
        "result": "[[1d8]] 5000 gp gems & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[1d10]] 2500 gp art objects & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[1d4]] 7500 gp art objects & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[1d8]] 5000 gp gems & [[1d4]] Magic Item Table H",
        "weight": null
      },
      {
        "result": "[[3d6]] 1000 gp gems & [[1d4]] Magic Item Table I",
        "weight": null
      },
      {
        "result": "[[1d10]] 2500 gp art objects & [[1d4]] Magic Item Table I",
        "weight": null
      },
      {
        "result": "[[1d4]] 7500 gp art objects & [[1d4]] Magic Item Table I",
        "weight": null
      },
      {
        "result": "[[1d8]] 5000 gp gems & [[1d4]] Magic Item Table I",
        "weight": null
      }
    ]
  }
];
