// Auto-generated by scripts/extract-data.ts — do not edit

export const DMG_INDIVIDUAL = [
  {
    "tier": "Individual Treasure: Challenge 0-4",
    "entries": [
      {
        "result": "[[5d6]] cp",
        "weight": 30
      },
      {
        "result": "[[4d6]] sp",
        "weight": 30
      },
      {
        "result": "[[3d6]] ep",
        "weight": 10
      },
      {
        "result": "[[3d6]] gp",
        "weight": 25
      },
      {
        "result": "[[1d6]] pp",
        "weight": 5
      }
    ]
  },
  {
    "tier": "Individual Treasure: Challenge 5-10",
    "entries": [
      {
        "result": "[[4d6*100]] cp & [[1d6*10]] gp",
        "weight": 30
      },
      {
        "result": "[[6d6*10]] sp & [[2d6*10]] gp",
        "weight": 30
      },
      {
        "result": "[[3d6*10]] ep & [[2d6*10]] gp",
        "weight": 10
      },
      {
        "result": "[[4d6*10]] gp",
        "weight": 25
      },
      {
        "result": "[[2d6*10]] gp * [[3d6]] pp",
        "weight": 5
      }
    ]
  },
  {
    "tier": "Individual Treasure: Challenge 11-16",
    "entries": [
      {
        "result": "[[4d6*100]] sp & [[1d6*100]] gp",
        "weight": 20
      },
      {
        "result": "[[1d6*100]] ep & [[1d6*100]] gp",
        "weight": 15
      },
      {
        "result": "[[2d6*100]] gp & [[1d6*10]] pp",
        "weight": 40
      },
      {
        "result": "[[2d6*100]] gp & [[2d6*10]] pp",
        "weight": 25
      }
    ]
  },
  {
    "tier": "Individual Treasure: Challenge 17+",
    "entries": [
      {
        "result": "[[2d6*1000]] ep & [[8d6*100]] gp",
        "weight": 15
      },
      {
        "result": "[[1d6*1000]] gp & [[1d6*100]] pp",
        "weight": 40
      },
      {
        "result": "[[1d6*1000]] gp & [[2d6*100]] pp",
        "weight": 45
      }
    ]
  }
];
