// Auto-generated by scripts/extract-data.ts — do not edit

export const MAGIC_ITEMS = {
  "Magic-Item-Table-A": [
    {
      "name": "[Potions-A]",
      "source": "",
      "weight": 40
    },
    {
      "name": "[Gear-A]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Spell-Scrolls-A]",
      "source": "",
      "weight": 10
    },
    {
      "name": "[Arms-Armor-A]",
      "source": "",
      "weight": 10
    },
    {
      "name": "[Spellcaster-A]",
      "source": "",
      "weight": 10
    },
    {
      "name": "[Trinkets-A]",
      "source": "",
      "weight": 10
    }
  ],
  "Magic-Item-Table-B": [
    {
      "name": "[Ammunition-B]",
      "source": "",
      "weight": 5
    },
    {
      "name": "[Consumables-B]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Items-B]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Potions-B]",
      "source": "",
      "weight": 50
    },
    {
      "name": "[Spells-B]",
      "source": "",
      "weight": 10
    }
  ],
  "Magic-Item-Table-C": [
    {
      "name": "[Ammunition-C]",
      "source": "",
      "weight": 5
    },
    {
      "name": "[Consumables-C]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Items-C]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Potions-C]",
      "source": "",
      "weight": 50
    },
    {
      "name": "[Spells-C]",
      "source": "",
      "weight": 10
    }
  ],
  "Magic-Item-Table-D": [
    {
      "name": "[Ammunition-D]",
      "source": "",
      "weight": 10
    },
    {
      "name": "[Consumables-D]",
      "source": "",
      "weight": 5
    },
    {
      "name": "[Items-D]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Potions-D]",
      "source": "",
      "weight": 50
    },
    {
      "name": "[Spells-D]",
      "source": "",
      "weight": 20
    }
  ],
  "Magic-Item-Table-E": [
    {
      "name": "[Ammunition-E]",
      "source": "",
      "weight": 5
    },
    {
      "name": "[Consumables-E]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Potions-E]",
      "source": "",
      "weight": 40
    },
    {
      "name": "[Spells-E]",
      "source": "",
      "weight": 40
    }
  ],
  "Magic-Item-Table-F": [
    {
      "name": "[Apparel-F]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Armor-F]",
      "source": "",
      "weight": 10
    },
    {
      "name": "[Arms-F]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Jewelry-F]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Misc-F]",
      "source": "",
      "weight": 25
    },
    {
      "name": "[Spellcaster-F]",
      "source": "",
      "weight": 15
    }
  ],
  "Magic-Item-Table-G": [
    {
      "name": "[Apparel-G]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Armor-G]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Arms-G]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Jewelry-G]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Misc-G]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Spellcaster-G]",
      "source": "",
      "weight": 20
    }
  ],
  "Figurine-of-Wondrous-Power-G": [
    {
      "name": "Bronze Griffon",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ebony Fly",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Golden Lions",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ivory Goats",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Marble Elephant",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Onyx Dog",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Serpentine Owl",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Magic-Item-Table-H": [
    {
      "name": "[Apparel-H]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Armor-H]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Arms-H]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Jewelry-H]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Misc-H]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Spellcaster-H]",
      "source": "",
      "weight": 15
    }
  ],
  "Magic-Item-Table-I": [
    {
      "name": "[Apparel-I]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Armor-I]",
      "source": "",
      "weight": 15
    },
    {
      "name": "[Arms-I]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Jewelry-I]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Misc-I]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Spellcaster-I]",
      "source": "",
      "weight": 10
    }
  ],
  "Magic-Armor-I": [
    {
      "name": "Armor, +2 half plate",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Armor, +2 plate",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Armor, +3 studded leather",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Armor, +3 breastplate",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Armor, +3 splint",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Armor, +3 half plate",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Armor, +3 plate",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Arms-Armor-A": [
    {
      "name": "[Weapons]",
      "source": "",
      "weight": 5
    },
    {
      "name": "Moon-Touched [Swords]",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Cast-Off Armor ([Cast-Off-Armor])",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Walloping [Ammunition]",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "[Metal-Armor] of Gleaming",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Smoldering [Smoldering-Armor] Armor",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "[Ammunition]",
      "source": "",
      "weight": 1
    },
    {
      "name": "Armblade ([Armblades])",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Veteran's Cane",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "[Armor]",
      "source": "",
      "weight": 1
    },
    {
      "name": "Shield",
      "source": "",
      "weight": 1
    },
    {
      "name": "Shield of Expression",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "[[1d4]] Unbreakable [Ammunition]",
      "source": "XGE",
      "weight": 1
    }
  ],
  "Gear-A": [
    {
      "name": "Bag of Holding",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Driftglobe",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Everbright Lantern",
      "source": "ERLW",
      "weight": 5
    },
    {
      "name": "Feather Token",
      "source": "ERLW",
      "weight": 5
    },
    {
      "name": "Horn of Silent Alarm",
      "source": "XGE",
      "weight": 5
    },
    {
      "name": "Clockwork Amulet",
      "source": "XGE",
      "weight": 5
    },
    {
      "name": "Shiftweave",
      "source": "ERLW",
      "weight": 5
    },
    {
      "name": "Thermal Cube",
      "source": "IWD",
      "weight": 5
    },
    {
      "name": "Lantern of Tracking [Creature-Type-A]",
      "source": "IWD",
      "weight": 4
    },
    {
      "name": "Breathing Bubble",
      "source": "EGW",
      "weight": 4
    },
    {
      "name": "Rope of Mending",
      "source": "XGE",
      "weight": 4
    },
    {
      "name": "Lock of Trickery",
      "source": "XGE",
      "weight": 4
    },
    {
      "name": "Chest of Preserving",
      "source": "WDMM",
      "weight": 4
    },
    {
      "name": "Orb of Direction",
      "source": "XGE",
      "weight": 4
    },
    {
      "name": "Orb of Time",
      "source": "XGE",
      "weight": 4
    },
    {
      "name": "Ear Horn of Hearing",
      "source": "XGE",
      "weight": 4
    },
    {
      "name": "Coin of Delving",
      "source": "EGW",
      "weight": 4
    },
    {
      "name": "Vox Seeker",
      "source": "EGW",
      "weight": 4
    },
    {
      "name": "Spellshard",
      "source": "ERLW",
      "weight": 4
    },
    {
      "name": "Cleansing Stone",
      "source": "ERLW",
      "weight": 4
    },
    {
      "name": "[Prosthesis]",
      "source": "",
      "weight": 4
    },
    {
      "name": "Mystery Key",
      "source": "XGE",
      "weight": 4
    },
    {
      "name": "Integrated [Tools]",
      "source": "ExE",
      "weight": 4
    }
  ],
  "Trinkets-A": [
    {
      "name": "Cloak of Billowing",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Wand of Smiles",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Pipe of Smoke Monsters",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Talking Doll",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Cloak of Many Fashions",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Hat of Vermin",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Pot of Awakening",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Charlatan's Die",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Staff of Adornment",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Staff of Birdcalls",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Staff of Flowers",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Wand of Conducting",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Wand of Pyrotechnics",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Wand of Scowls",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Perfume of Bewitching",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Pole of Angling",
      "source": "XGE",
      "weight": 3
    },
    {
      "name": "Clothes of Mending",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Common Glamerweave",
      "source": "ERLW",
      "weight": 2
    },
    {
      "name": "Uncommon Glamerweave",
      "source": "ERLW",
      "weight": 2
    },
    {
      "name": "Masquerade Tattoo",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Gem of Light",
      "source": "",
      "weight": 2
    },
    {
      "name": "Masque Charm",
      "source": "SCC",
      "weight": 2
    },
    {
      "name": "[[4d4]] Beads of Refreshment",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "[[1d4]] Beads of Nourishment",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Bottle of Boundless Coffee",
      "source": "SCC",
      "weight": 2
    },
    {
      "name": "Tankard of Plenty",
      "source": "ToD",
      "weight": 2
    },
    {
      "name": "Heward's Handy Spice Pouch",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Tankard of Sobriety",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Charlatan's Gloves",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Drybrooch",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Duster",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Lamplighter",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Spark",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Talking Wand",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Thurimbar Rod",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Boots of False Tracks",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Candle of the Deep",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Doublet of Dramatic Demise",
      "source": "TDCS",
      "weight": 2
    },
    {
      "name": "Dread Helm",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Illuminator's Tattoo",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Pipe of Remembrance",
      "source": "GoS",
      "weight": 2
    },
    {
      "name": "Pole of Collapsing",
      "source": "XGE",
      "weight": 2
    }
  ],
  "Potions-A": [
    {
      "name": "Potion of Healing",
      "source": "DMG",
      "weight": 12
    },
    {
      "name": "Potion of Climbing",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Potion of Comprehension",
      "source": "WDMM",
      "weight": 2
    },
    {
      "name": "Potion of Watchful Rest",
      "source": "WDMM",
      "weight": 2
    },
    {
      "name": "Potion of Greater Healing",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Spell-Scrolls-A": [
    {
      "name": "Spell Scroll ([Spells-Cantrip])",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Spell Scroll ([Spells-Level-1])",
      "source": "DMG",
      "weight": 9
    },
    {
      "name": "Spell Scroll ([Spells-Level-2])",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Cantrip])",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-1])",
      "source": "TCE",
      "weight": 3
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-2])",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Cast-Off-Armor": [
    {
      "name": "[Light-Armor]",
      "source": "",
      "weight": 2
    },
    {
      "name": "[Medium-Armor]",
      "source": "",
      "weight": 3
    },
    {
      "name": "[Heavy-Armor]",
      "source": "",
      "weight": 1
    }
  ],
  "Smoldering-Armor": [
    {
      "name": "[Light-Armor]",
      "source": "",
      "weight": 5
    },
    {
      "name": "[Medium-Armor]",
      "source": "",
      "weight": 5
    },
    {
      "name": "[Heavy-Armor]",
      "source": "",
      "weight": 2
    }
  ],
  "Creature-Type-A": [
    {
      "name": "Aberrations",
      "source": "",
      "weight": 1
    },
    {
      "name": "Celestials",
      "source": "",
      "weight": 1
    },
    {
      "name": "Constructs",
      "source": "",
      "weight": 1
    },
    {
      "name": "Dragons",
      "source": "",
      "weight": 1
    },
    {
      "name": "Elementals",
      "source": "",
      "weight": 1
    },
    {
      "name": "Fey",
      "source": "",
      "weight": 1
    },
    {
      "name": "Fiends",
      "source": "",
      "weight": 1
    },
    {
      "name": "Giants",
      "source": "",
      "weight": 1
    },
    {
      "name": "Monstrosities",
      "source": "",
      "weight": 1
    },
    {
      "name": "Undead",
      "source": "",
      "weight": 1
    }
  ],
  "Spellcaster-A": [
    {
      "name": "[Orb-of-Shielding] of Shielding ([Planar-Stone])",
      "source": "ERLW",
      "weight": 4
    },
    {
      "name": "Imbued [Imbued-Wood] ([Planar-Wood])",
      "source": "ERLW",
      "weight": 3
    },
    {
      "name": "Battle Rod",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Dark Shard Amulet",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Ruby of the War Mage",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "War Staff",
      "source": "ExE",
      "weight": 2
    },
    {
      "name": "Enduring Spellbook",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Hat of Wizardry",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Instrument of Illusions",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Instrument of Scribing",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Wand Sheath ([Wands-A])",
      "source": "ERLW",
      "weight": 1
    }
  ],
  "Orb-of-Shielding": [
    {
      "name": "Crystal",
      "source": "",
      "weight": 2
    },
    {
      "name": "Orb",
      "source": "",
      "weight": 2
    }
  ],
  "Planar-Stone": [
    {
      "name": "Fernian Basalt - Fire",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Irian Quartz - Radiant",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Kythrian Skarn - Acid and Poison",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Lamannian Flint - Lightning and Thunder",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Mabaran Obsidian - Necrotic",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Risian Shale - Cold",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Shavarran Chert - Force",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Xorian Marble - Psychic",
      "source": "ERLW",
      "weight": 1
    }
  ],
  "Imbued-Wood": [
    {
      "name": "Rod",
      "source": "",
      "weight": 2
    },
    {
      "name": "Staff",
      "source": "",
      "weight": 2
    },
    {
      "name": "Wand",
      "source": "",
      "weight": 2
    }
  ],
  "Planar-Wood": [
    {
      "name": "Fernian Ash - Fire",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Irian Rosewood - Radiant",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Kythrian Manchineel - Acid and Poison",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Lamannian Oak - Lightning and Thunder",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Mabaran Ebony - Necrotic",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Risian Pine - Cold",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Shavarran Birch - Force",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Xorian Wenge - Psychic",
      "source": "ERLW",
      "weight": 1
    }
  ],
  "Prosthesis": [
    {
      "name": "Ersatz Eye",
      "source": "XGE",
      "weight": 2
    },
    {
      "name": "Prosthetic Left Hand",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Prosthetic Right Hand",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Prosthetic Left Arm",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Prosthetic Right Arm",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Prosthetic Left Foot",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Prosthetic Right Foot",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Prosthetic Left Leg",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Prosthetic Right Leg",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Armblades": [
    {
      "name": "[Armblades-Simple]",
      "source": "",
      "weight": 2
    },
    {
      "name": "[Armblades-Martial]",
      "source": "",
      "weight": 4
    }
  ],
  "Armblades-Simple": [
    {
      "name": "Dagger",
      "source": "",
      "weight": 4
    },
    {
      "name": "Spear",
      "source": "",
      "weight": 3
    },
    {
      "name": "Mace",
      "source": "",
      "weight": 2
    },
    {
      "name": "Club",
      "source": "",
      "weight": 1
    },
    {
      "name": "Handaxe",
      "source": "",
      "weight": 1
    },
    {
      "name": "Sickle",
      "source": "",
      "weight": 1
    }
  ],
  "Armblades-Martial": [
    {
      "name": "Longsword",
      "source": "",
      "weight": 4
    },
    {
      "name": "Shortsword",
      "source": "",
      "weight": 4
    },
    {
      "name": "Battleaxe",
      "source": "",
      "weight": 2
    },
    {
      "name": "Flail",
      "source": "",
      "weight": 2
    },
    {
      "name": "Rapier",
      "source": "",
      "weight": 2
    },
    {
      "name": "Warhammer",
      "source": "",
      "weight": 2
    },
    {
      "name": "Morningstar",
      "source": "",
      "weight": 1
    },
    {
      "name": "Scimitar",
      "source": "",
      "weight": 1
    },
    {
      "name": "War Pick",
      "source": "",
      "weight": 1
    },
    {
      "name": "Whip",
      "source": "",
      "weight": 1
    }
  ],
  "Wands-A": [
    {
      "name": "Wand of Magic Detection",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Wand of Secrets",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Wand of Entangle",
      "source": "TYP",
      "weight": 3
    },
    {
      "name": "Wand of Magic Missiles",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Conducting",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Wand of Pyrotechnics",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Wand of Scowls",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Wand of Smiles",
      "source": "XGE",
      "weight": 1
    },
    {
      "name": "Wand of Web",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Consumables-B": [
    {
      "name": "Keoghtom's Ointment",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Elemental Gem, [Gems-B]",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Oil of Slipperiness",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Dust of Deliciousness",
      "source": "EGW",
      "weight": 2
    },
    {
      "name": "Dust of Disappearance",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Pixie Dust",
      "source": "WBtW",
      "weight": 2
    },
    {
      "name": "Bottled Breath",
      "source": "PoTA",
      "weight": 1
    },
    {
      "name": "Dust of Corrosion",
      "source": "WBtW",
      "weight": 1
    },
    {
      "name": "Dust of Dryness",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Philter of Love",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Gems-B": [
    {
      "name": "Blue Sapphire",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Emerald",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Red Corundum",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Yellow Diamond",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Items-B": [
    {
      "name": "Uncommon Glamerweave",
      "source": "ERLW",
      "weight": 10
    },
    {
      "name": "Bag of Holding",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Gloves of Storing",
      "source": "ExE",
      "weight": 6
    },
    {
      "name": "Mithral [Metal-Armor]",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Balloon Pack",
      "source": "PotA",
      "weight": 3
    },
    {
      "name": "Cap of Water Breathing",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Cloak of the Manta Ray",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Echo Stone",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Emerald Pen",
      "source": "FTD",
      "weight": 3
    },
    {
      "name": "Goggles of Night",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Helm of Comprehending Languages",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "House of Cards",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Immovable Rod",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Lantern of Revealing",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Mariner's [Armor]",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Propeller Helm",
      "source": "WDMM",
      "weight": 3
    },
    {
      "name": "Ring of Swimming",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Robe of Serpents",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Robe of Useful Items",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Rope of Climbing",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Saddle of the Cavalier",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "[[1d4]] Seeker Dart",
      "source": "PotA",
      "weight": 3
    },
    {
      "name": "Serpent Scale Armor",
      "source": "CM",
      "weight": 3
    },
    {
      "name": "Storm Boomerang",
      "source": "PotA",
      "weight": 3
    },
    {
      "name": "Wand of Entangle",
      "source": "TYP",
      "weight": 3
    },
    {
      "name": "Wand of Magic Detection",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Wand of Secrets",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Alchemy Jug",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Alchemy Jug (Blue)",
      "source": "CM",
      "weight": 1
    },
    {
      "name": "Alchemy Jug (Orange)",
      "source": "CM",
      "weight": 1
    }
  ],
  "Potions-B": [
    {
      "name": "Potion of Greater Healing",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Potion of [MM-Breath] Breath",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Potion of [Damage-Type] Resistance",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Potion of Animal Friendship",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Hill Giant Strength",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Growth",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Water Breathing",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Advantage",
      "source": "WBtW",
      "weight": 1
    }
  ],
  "Spells-B": [
    {
      "name": "Spell Scroll ([Spells-Level-2])",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Spell Scroll ([Spells-Level-3])",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-2])",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-3])",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Ammunition-B": [
    {
      "name": "[Ammunition], +1",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Dried Leech [Ammunition]",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Winged [Ammunition]",
      "source": "BMT",
      "weight": 2
    }
  ],
  "Apparel-F": [
    {
      "name": "Boots of Elvenkind",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Boots of Springing and Striding",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Boots of the Vigilant",
      "source": "TDCS",
      "weight": 4
    },
    {
      "name": "Boots of the Winterlands",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Bracers of Archery",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Cloak of Elvenkind",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Cloak of Protection",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Coiling Grasp Tattoo",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Dragonhide Belt, +1",
      "source": "FTD",
      "weight": 4
    },
    {
      "name": "Gauntlets of Ogre Power",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Gloves of Missile Snaring",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Gloves of Swimming and Climbing",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Gloves of Thievery",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Goggles of Object Reading",
      "source": "EGW",
      "weight": 4
    },
    {
      "name": "Hat of Disguise",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Headband of Intellect",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Living Gloves",
      "source": "ERLW",
      "weight": 4
    },
    {
      "name": "Robe of Summer",
      "source": "TYP",
      "weight": 4
    },
    {
      "name": "Slippers of Spider Climbing",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Slumbering Scaled Ornament",
      "source": "FTD",
      "weight": 4
    },
    {
      "name": "Small Barrier Tattoo",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Winged Boots",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Eyes of Charming",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Eyes of the Eagle",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Helm of Telepathy",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Helm of Underwater Action",
      "source": "GoS",
      "weight": 3
    }
  ],
  "Armor-F": [
    {
      "name": "[Armor] of Weightlessness",
      "source": "BMT",
      "weight": 5
    },
    {
      "name": "Adamantine [Metal-Armor]",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "[Metal-Armor] of the Fallen",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Boomerang Shield",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Sentinel Shield",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Shield, +1",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "[Heavy-Armor] of Knight's Fellowship",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "[Medium-Armor] of Fungal Spores",
      "source": "BMT",
      "weight": 1
    }
  ],
  "Arms-F": [
    {
      "name": "[Weapons], +1",
      "source": "DMG",
      "weight": 20
    },
    {
      "name": "[Weapons] of Warning",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Dragon Wing [Dragon-Breath] [Bows]",
      "source": "FTD",
      "weight": 6
    },
    {
      "name": "Gauntlets of Flaming Fury",
      "source": "DIA",
      "weight": 6
    },
    {
      "name": "Hungry [Weapons]",
      "source": "ExE",
      "weight": 6
    },
    {
      "name": "Quiver of Ehlonna",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Vicious [Weapons]",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Bloodrage Greataxe",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Crawling Gauntlet",
      "source": "ExE",
      "weight": 3
    },
    {
      "name": "Dagger of Blindsight",
      "source": "WDMM",
      "weight": 3
    },
    {
      "name": "Eldritch Claw Tattoo",
      "source": "TCE",
      "weight": 3
    },
    {
      "name": "Hew",
      "source": "LMoP",
      "weight": 3
    },
    {
      "name": "Javelin of Lightning",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Lightbringer",
      "source": "LMoP",
      "weight": 3
    },
    {
      "name": "Needle of Mending",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Rod of Mercurial Form",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Sling of Giant Felling",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Slumbering [Dragon-Breath] Dragon's Wrath [Weapons]",
      "source": "FTD",
      "weight": 3
    },
    {
      "name": "Throwing Scarab",
      "source": "ExE",
      "weight": 3
    },
    {
      "name": "Tongueworm",
      "source": "ExE",
      "weight": 3
    },
    {
      "name": "Wraps of Unarmed Prowess, +1",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Trident of Fish Command",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Jewelry-F": [
    {
      "name": "[Ioun-Stones-G]",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Amulet of Health",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Amulet of Proof against Detection and Location",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Amulet of the Drunkard",
      "source": "EGW",
      "weight": 1
    },
    {
      "name": "Brooch of Living Essence",
      "source": "EGW",
      "weight": 1
    },
    {
      "name": "Brooch of Shielding",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Fabulist Gem",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Medallion of Thoughts",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Necklace of Adaptation",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Periapt of Wound Closure",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ring of Jumping",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ring of Mind Shielding",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ring of Obscuring",
      "source": "EGW",
      "weight": 1
    },
    {
      "name": "Ring of Protection",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ring of Puzzler's Wit",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Ring of Truth Telling",
      "source": "WDH",
      "weight": 1
    },
    {
      "name": "Ring of Warmth",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ring of Water Walking",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Ioun-Stones-G": [
    {
      "name": "Ioun Stone (awareness)",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ioun Stone (protection)",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ioun Stone (reserve)",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ioun Stone (sustenance)",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Misc-F": [
    {
      "name": "Balance of Harmony",
      "source": "TYP",
      "weight": 5
    },
    {
      "name": "Earworm",
      "source": "ERLW",
      "weight": 5
    },
    {
      "name": "Feather of Diatryma Summoning",
      "source": "WDH",
      "weight": 5
    },
    {
      "name": "Gem of Brightness",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Ghost Lantern",
      "source": "ToA",
      "weight": 5
    },
    {
      "name": "Night Caller",
      "source": "TYP",
      "weight": 5
    },
    {
      "name": "Prehistoric Figurine of Wondrous Power (Pyrite Plesiosaurus)",
      "source": "BGG",
      "weight": 5
    },
    {
      "name": "Wandering Eye",
      "source": "ExE",
      "weight": 5
    },
    {
      "name": "Card Sharp's Deck",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Deck of Miscellany",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Deck of Wonder",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Pyroconverger",
      "source": "GGR",
      "weight": 3
    },
    {
      "name": "Rod of Retribution",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Rod of the Vonindod (Finding)",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Scissors of Shadow Snipping",
      "source": "WBtW",
      "weight": 3
    },
    {
      "name": "Siren Song Lyre",
      "source": "MOT",
      "weight": 3
    },
    {
      "name": "Stone of Good Luck",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Wand of Magic Missiles",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Wand of Web",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "War Horn of Valor",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "[Bag-of-Tricks-F]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Broom of Flying",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Circlet of Blasting",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Deck of Illusions ([[34-1d20-1]] cards)",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Eversmoking Bottle",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Figurine of Wondrous Power (Silver Raven)",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Pipes of Haunting",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Pipes of the Sewers",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Skysail",
      "source": "TDCS",
      "weight": 2
    },
    {
      "name": "Slumbering Dragon Vessel",
      "source": "FTD",
      "weight": 2
    },
    {
      "name": "Spies' Murmur",
      "source": "GGR",
      "weight": 2
    },
    {
      "name": "Wind Fan",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Bag-of-Tricks-F": [
    {
      "name": "Bag of Tricks (gray)",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Bag of Tricks (rust)",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Bag of tricks (tan)",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Spellcaster-F": [
    {
      "name": "All-Purpose Tool, +1",
      "source": "TCE",
      "weight": 8
    },
    {
      "name": "Arcane Grimoire, +1",
      "source": "TCE",
      "weight": 8
    },
    {
      "name": "Pearl of Power",
      "source": "DMG",
      "weight": 8
    },
    {
      "name": "Rod of the Pact Keeper, +1",
      "source": "DMG",
      "weight": 8
    },
    {
      "name": "Skyblinder Staff",
      "source": "GGR",
      "weight": 8
    },
    {
      "name": "Spellburrow",
      "source": "ExE",
      "weight": 8
    },
    {
      "name": "Tools of the Master, +1",
      "source": "ExE",
      "weight": 8
    },
    {
      "name": "Amulet of the Devout, +1",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Bloodwell Vial, +1",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Feywild Shard",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Guardian Emblem",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Moon Sickle, +1",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Nature's Mantle",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Slumbering Dragon-Touched Focus",
      "source": "FTD",
      "weight": 4
    },
    {
      "name": "Wand of the War Mage, +1",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Instrument of the Bards (Doss Lute)",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Instrument of the Bards (Fochlucan Bandore)",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Instrument of the Bards (Mac-Fuimidh Cittern)",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Rhythm-Maker's Drum, +1",
      "source": "TCE",
      "weight": 3
    }
  ],
  "Consumables-C": [
    {
      "name": "Scroll of Protection Against [Creature-Type-C]",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Glowrune Pigment",
      "source": "BGG",
      "weight": 2
    },
    {
      "name": "Quaal's Feather Token, [Feather-Token-C]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Bag of Beans",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Bead of Force",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Black Chromatic Rose",
      "source": "WBtW",
      "weight": 1
    },
    {
      "name": "Blue Chromatic Rose",
      "source": "WBtW",
      "weight": 1
    },
    {
      "name": "Green Chromatic Rose",
      "source": "WBtW",
      "weight": 1
    },
    {
      "name": "Necklace of Fireballs",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Oil of Etherealness",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Red Chromatic Rose",
      "source": "WBtW",
      "weight": 1
    },
    {
      "name": "Teleportation Tablet",
      "source": "CotN",
      "weight": 1
    },
    {
      "name": "White Chromatic Rose",
      "source": "WBtW",
      "weight": 1
    }
  ],
  "Creature-Type-C": [
    {
      "name": "Aberrations",
      "source": "",
      "weight": 10
    },
    {
      "name": "Beasts",
      "source": "",
      "weight": 10
    },
    {
      "name": "Celestials",
      "source": "",
      "weight": 10
    },
    {
      "name": "Elementals",
      "source": "",
      "weight": 10
    },
    {
      "name": "Fey",
      "source": "",
      "weight": 10
    },
    {
      "name": "Fiends",
      "source": "",
      "weight": 25
    },
    {
      "name": "Plants",
      "source": "",
      "weight": 5
    },
    {
      "name": "Undead",
      "source": "",
      "weight": 20
    }
  ],
  "Feather-Token-C": [
    {
      "name": "Anchor",
      "source": "DMG",
      "weight": 20
    },
    {
      "name": "Bird",
      "source": "DMG",
      "weight": 15
    },
    {
      "name": "Fan",
      "source": "DMG",
      "weight": 15
    },
    {
      "name": "Swan Boat",
      "source": "DMG",
      "weight": 15
    },
    {
      "name": "Tree",
      "source": "DMG",
      "weight": 25
    },
    {
      "name": "Whip",
      "source": "DMG",
      "weight": 10
    }
  ],
  "Items-C": [
    {
      "name": "Eagle Whistle",
      "source": "TYP",
      "weight": 2
    },
    {
      "name": "Heward's Handy Haversack",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Hook of Fisher's Delight",
      "source": "IWD",
      "weight": 2
    },
    {
      "name": "Mirror of the Past",
      "source": "TYP",
      "weight": 2
    },
    {
      "name": "Professor Orb",
      "source": "WDMM",
      "weight": 2
    },
    {
      "name": "Sending Stones",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Cauldron of Plenty",
      "source": "IWD",
      "weight": 1
    },
    {
      "name": "Chime of Opening",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Decanter of Endless Water",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Dodecahedron of Doom",
      "source": "WDMM",
      "weight": 1
    },
    {
      "name": "Eyes of Minute Seeing",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Folding Boat",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Horseshoes of Speed",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Periapt of Health",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Potions-C": [
    {
      "name": "Potion of Superior Healing",
      "source": "DMG",
      "weight": 30
    },
    {
      "name": "Elixir of Health",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Aqueous Form",
      "source": "MOT",
      "weight": 5
    },
    {
      "name": "Potion of Clairvoyance",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Diminution",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Fire Giant Strength",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Frost Giant Strength",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Gaseous Form",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Heroism",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Invulnerability",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Maximum Power",
      "source": "EGW",
      "weight": 5
    },
    {
      "name": "Potion of Mind Control (Beast)",
      "source": "TYP",
      "weight": 5
    },
    {
      "name": "Potion of Mind Control (Humanoid)",
      "source": "TYP",
      "weight": 5
    },
    {
      "name": "Potion of Mind Reading",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Potion of Stone Giant Strength",
      "source": "DMG",
      "weight": 5
    }
  ],
  "Spells-C": [
    {
      "name": "Spell Scroll ([Spells-Level-4])",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Spell Scroll ([Spells-Level-5])",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-4])",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-5])",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Ammunition-C": [
    {
      "name": "[Ammunition], +2",
      "source": "DMG",
      "weight": 6
    }
  ],
  "Apparel-G": [
    {
      "name": "Bracers of Defense",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Dragonhide Belt, +2",
      "source": "FTD",
      "weight": 6
    },
    {
      "name": "Kagonesti Forest Shroud",
      "source": "DL",
      "weight": 6
    },
    {
      "name": "Medium Barrier Tattoo",
      "source": "TCE",
      "weight": 6
    },
    {
      "name": "Shadow Sibling",
      "source": "ExE",
      "weight": 6
    },
    {
      "name": "Shadowfell Brand Tattoo",
      "source": "TCE",
      "weight": 6
    },
    {
      "name": "Belt of Dwarvenkind",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Belt of Hill Giant Strength",
      "source": "DMG",
      "weight": 5
    },
    {
      "name": "Boots of Levitation",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Boots of Speed",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Bracers of Celerity",
      "source": "PaB",
      "weight": 3
    },
    {
      "name": "Butcher's Bib",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Cape of the Mountebank",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Cloak of Displacement",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Cloak of the Bat",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Coat of the Crest",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Crown of the Wrath Bringer",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Delver's Claws",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Helm of Teleportation",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Helm of the Gods",
      "source": "MOT",
      "weight": 3
    },
    {
      "name": "Mantle of Spell Resistance",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Robe of Eyes",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Rogue's Mantle",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Stirring Scaled Ornament",
      "source": "FTD",
      "weight": 3
    },
    {
      "name": "Stormrider Boots",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Wayfarer's Boots",
      "source": "BGG",
      "weight": 3
    }
  ],
  "Armor-G": [
    {
      "name": "[Armor] of [Damage-Type] Resistance",
      "source": "DMG",
      "weight": 12
    },
    {
      "name": "[Armor], +1",
      "source": "DMG",
      "weight": 12
    },
    {
      "name": "Breastplate of Balance",
      "source": "BMT",
      "weight": 8
    },
    {
      "name": "Elven Chain Shirt, +1",
      "source": "DMG",
      "weight": 8
    },
    {
      "name": "Feywrought [Armor]",
      "source": "BMT",
      "weight": 8
    },
    {
      "name": "Glamoured Studded Leather, +1",
      "source": "DMG",
      "weight": 8
    },
    {
      "name": "Gloomwrought Armor [Armor]",
      "source": "BMT",
      "weight": 8
    },
    {
      "name": "Molten Bronze Skin [Molten-Armor-G]",
      "source": "MOT",
      "weight": 8
    },
    {
      "name": "Zephyr [Light-Armor]",
      "source": "BGG",
      "weight": 8
    },
    {
      "name": "Arrow-Catching Shield",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Battering Shield",
      "source": "EGW",
      "weight": 4
    },
    {
      "name": "Pariah's Shield",
      "source": "GGR",
      "weight": 4
    },
    {
      "name": "Shield of Missile Attraction",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Shield, +2",
      "source": "DMG",
      "weight": 4
    }
  ],
  "Molten-Armor-G": [
    {
      "name": "Half Plate Armor",
      "source": "",
      "weight": 2
    },
    {
      "name": "Plate Armor",
      "source": "",
      "weight": 2
    }
  ],
  "Arms-G": [
    {
      "name": "[Weapons], +2",
      "source": "DMG",
      "weight": 10
    },
    {
      "name": "Arcane Propulsion Arm",
      "source": "ERLW",
      "weight": 3
    },
    {
      "name": "Bonecounter",
      "source": "SDW",
      "weight": 3
    },
    {
      "name": "Bracer of Flying Daggers",
      "source": "WDH",
      "weight": 3
    },
    {
      "name": "Donjon's Sundering Sphere",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Glimmering Moon [Bows]",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Lash of Immolation",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Oceanic [Ranged]",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Staff of the Rooted Hills",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Starshot [Bows]",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Two-Birds Sling",
      "source": "MOT",
      "weight": 3
    },
    {
      "name": "[Bows] of Conflagration",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "[Swords] of Life Stealing",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "[Swords] of Wounding",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "[Weapons] of Certain Death",
      "source": "EGW",
      "weight": 2
    },
    {
      "name": "Acheron [Swords]",
      "source": "EGW",
      "weight": 2
    },
    {
      "name": "Corpse Slayer [Weapons]",
      "source": "EGW",
      "weight": 2
    },
    {
      "name": "Crystal [Swords]",
      "source": "FTD",
      "weight": 2
    },
    {
      "name": "Dagger of Denial",
      "source": "EGW",
      "weight": 2
    },
    {
      "name": "Dagger of Venom",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Dragon Slayer [Swords]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Flame Tongue [Swords]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Flayer Slayer",
      "source": "PaB",
      "weight": 2
    },
    {
      "name": "Frost Brand [Swords]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Giant Slayer [Giant-Slayer-G]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Grasping Whip",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Inescapable Lash",
      "source": "TDCS",
      "weight": 2
    },
    {
      "name": "Luminous War Pick",
      "source": "PaB",
      "weight": 2
    },
    {
      "name": "Mace of Disruption",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Mace of Smiting",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Mace of Terror",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Magician's Judge",
      "source": "TDCS",
      "weight": 2
    },
    {
      "name": "Ruinous Flail",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Serpent's Fang",
      "source": "CM",
      "weight": 2
    },
    {
      "name": "Stirring Dragon's Wrath [Dragon-Breath] [Weapons]",
      "source": "FTD",
      "weight": 2
    },
    {
      "name": "Summer's Dance",
      "source": "TDCS",
      "weight": 2
    },
    {
      "name": "Sun Blade",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Sunforger",
      "source": "GGR",
      "weight": 2
    },
    {
      "name": "Warrior's Passkey",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Woodcutter's Axe",
      "source": "WBtW",
      "weight": 2
    },
    {
      "name": "Wraps of Unarmed Prowess, +2",
      "source": "BMT",
      "weight": 2
    }
  ],
  "Giant-Slayer-G": [
    {
      "name": "[Axes]",
      "source": "",
      "weight": 4
    },
    {
      "name": "[Swords]",
      "source": "",
      "weight": 2
    }
  ],
  "Jewelry-G": [
    {
      "name": "Ring of [Damage-Type-Gem-G]",
      "source": "DMG",
      "weight": 30
    },
    {
      "name": "[Ioun-Stone-H]",
      "source": "DMG",
      "weight": 10
    },
    {
      "name": "Amulet of Protection from Turning",
      "source": "TYP",
      "weight": 4
    },
    {
      "name": "Charm of Plant Command",
      "source": "GoS",
      "weight": 4
    },
    {
      "name": "Necklace of Prayer Beads",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Periapt of Proof Against Poison",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of Animal Influence",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of Evasion",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of Feather Falling",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of Free Action",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of Protection, +2",
      "source": "TDCS",
      "weight": 4
    },
    {
      "name": "Ring of Spell Storing",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of Temporal Salvation",
      "source": "EGW",
      "weight": 4
    },
    {
      "name": "Ring of the Ram",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of X-Ray Vision",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Sage's Serpent Signet",
      "source": "BMT",
      "weight": 4
    },
    {
      "name": "Sage's Songbird Signet",
      "source": "BMT",
      "weight": 4
    }
  ],
  "Damage-Type-Gem-G": [
    {
      "name": "Acid Resistance, set with pearl",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Cold Resistance, set with tourmaline",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Fire Resistance, set with garnet",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Force Resistance, set with sapphire",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Lightning Resistance, set with citrine",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Necrotic Resistance, set with jet",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Poison Resistance, set with amethyst",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Psychic Resistace, set with jade",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Radiant Resistance, set with topaz",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Thunder Resistance, set with spinel",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Ioun-Stone-H": [
    {
      "name": "Ioun Stone of Agility",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Ioun Stone of Fortitude",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Ioun Stone of Insight",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Ioun Stone of Intellect",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Ioun Stone of Leadership",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Ioun Stone of Strength",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Ioun Stone of Absorption",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Misc-G": [
    {
      "name": "Docent",
      "source": "ERLW",
      "weight": 10
    },
    {
      "name": "Banner of the Krig Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Bowl of Commanding Water Elementals",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Brazier of Commanding Fire Elementals",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Censer of Controlling Air Elementals",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Claw of the Wyrm Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Deck of Oracles",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Earthboard",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Flamefriend Lantern",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Flying Chariot",
      "source": "MOT",
      "weight": 3
    },
    {
      "name": "Gavel of the Venn Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Opal of the Ild Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Orb of the Stein Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Prehistoric Figurine of Wondrous Power, Kyanite Pteranodon",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Weird Tank",
      "source": "PotA",
      "weight": 3
    },
    {
      "name": "[Figurine-of-Wondrous-Power-G]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "[Horn-of-Valhalla-G] Horn of Valhalla",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Cube of Force",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Daern's Instant Fortress",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Dimensional Shackles",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Gem of Seeing",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Horn of Blasting",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Iron Bands of Bilarro",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Ornithopter of Flying",
      "source": "WBtW",
      "weight": 2
    },
    {
      "name": "Rod of Rulership",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Rope of Entanglement",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Stirring Dragon Vessel",
      "source": "FTD",
      "weight": 2
    },
    {
      "name": "Stone of Controlling Earth Elementals",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Stonespeaker Crystal",
      "source": "OotA",
      "weight": 2
    },
    {
      "name": "Tentacle Rod",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Binding",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Enemy Detection",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Fear",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Fireballs",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Lightning Bolts",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Paralysis",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Winter",
      "source": "ToD",
      "weight": 2
    },
    {
      "name": "Wand of Wonder",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wings of Flying",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Horn-of-Valhalla-G": [
    {
      "name": "Silver",
      "source": "DMG",
      "weight": 8
    },
    {
      "name": "Brass",
      "source": "DMG",
      "weight": 7
    },
    {
      "name": "[Horn-of-Valhalla-G]",
      "source": "",
      "weight": 5
    }
  ],
  "Spellcaster-G": [
    {
      "name": "[Sorcerer-G]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Wizard-G]",
      "source": "",
      "weight": 20
    },
    {
      "name": "[Bard-G]",
      "source": "",
      "weight": 6
    },
    {
      "name": "All-Purpose Tool, +2",
      "source": "TCE",
      "weight": 6
    },
    {
      "name": "Staff of Charming",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Staff of Healing",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Staff of Swarming Insects",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Staff of the Ivory Claw",
      "source": "EGW",
      "weight": 4
    },
    {
      "name": "Staff of the Woodlands",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Staff of Withering",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Rod of the Pact Keeper, +2",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Staff of Defense",
      "source": "LMoP",
      "weight": 3
    },
    {
      "name": "Stirring [FTD-Dragons]-Dragon-Touched Focus",
      "source": "FTD",
      "weight": 3
    },
    {
      "name": "Wand of the War Mage, +2",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Amulet of the Devout, +2",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Bell Branch",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Devotee's Censer",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Fate Dealer's Deck, +1",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Moon Sickle, +2",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Sun Staff",
      "source": "BMT",
      "weight": 2
    }
  ],
  "Sorcerer-G": [
    {
      "name": "Bloodwell Vial, +2",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Chaotic Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Evil Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Good Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Lawful Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Air Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Earth Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Fire Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Water Essence Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Astral Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Far Realm Shard",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Shadowfell Shard",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Wizard-G": [
    {
      "name": "Arcane Grimoire, +2",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Alchemical Compendium",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Astromancy Archive",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Atlas of Endless Horizons",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Duplicitous Manuscript",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Fulminating Treatise",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Heart Weaver's Primer",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Libram of Souls and Flesh",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Planecaller's Codex",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Protective Verses",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Bard-G": [
    {
      "name": "Rhythm-Maker's Drum, +2",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Instrument of the Bards (Canaith mandolin)",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Instrument of the Bards (Cli lyre)",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Lyre of Building",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Reveler's Concertina",
      "source": "TCE",
      "weight": 2
    }
  ],
  "Ammunition-D": [
    {
      "name": "[Ammunition], +3",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Bloodseeker [Ammunition]",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Cataclysm Bolts",
      "source": "TDCS",
      "weight": 1
    },
    {
      "name": "Sling Bullets of Althemone",
      "source": "MOT",
      "weight": 1
    }
  ],
  "Consumables-D": [
    {
      "name": "Dispelling Stone",
      "source": "EGW",
      "weight": 2
    },
    {
      "name": "Oil of Sharpness",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Nolzur's Marvelous Pigments",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Reincarnation Dust",
      "source": "EGW",
      "weight": 1
    }
  ],
  "Items-D": [
    {
      "name": "Abracadabrus",
      "source": "IWD",
      "weight": 2
    },
    {
      "name": "Fish Suit",
      "source": "AAG",
      "weight": 2
    },
    {
      "name": "Horseshoes of a Zephyr",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Raven's Slumber",
      "source": "TDCS",
      "weight": 2
    },
    {
      "name": "Bag of Devouring",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Mirror of Infinite Transpondence",
      "source": "TDCS",
      "weight": 1
    },
    {
      "name": "Mudslick Tower",
      "source": "PaB",
      "weight": 1
    },
    {
      "name": "Portable Hole",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Potions-D": [
    {
      "name": "Potion of Supreme Healing",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Potion of Cloud Giant Strength",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Flying",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Invisibility",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Longevity",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Mind Control (Monster)",
      "source": "TYP",
      "weight": 1
    },
    {
      "name": "Potion of Possibility",
      "source": "EGW",
      "weight": 1
    },
    {
      "name": "Potion of Speed",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Potion of Vitality",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Spells-D": [
    {
      "name": "Spell Scroll ([Spells-Level-6])",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Spell Scroll ([Spells-Level-7])",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Spell Scroll ([Spells-Level-8])",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-6])",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-7])",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-8])",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Apparel-H": [
    {
      "name": "[Absorbing-H] Tattoo",
      "source": "TCE",
      "weight": 8
    },
    {
      "name": "Belt of [Giant-H] Giant Strength",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Belt of Fire Giant Strength",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Boots of Haste",
      "source": "TDCS",
      "weight": 4
    },
    {
      "name": "Cape of Enlargement",
      "source": "PaB",
      "weight": 4
    },
    {
      "name": "Cloak of Arachnida",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Crown of Whirling Comets",
      "source": "BMT",
      "weight": 4
    },
    {
      "name": "Dragonhide Belt, +3",
      "source": "FTD",
      "weight": 4
    },
    {
      "name": "Ghost Step Tattoo",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Helm of Brilliance",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Illusionist's Bracers",
      "source": "GGR",
      "weight": 4
    },
    {
      "name": "Large Barrier Tattoo",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Lifewell Tattoo",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Mindblasting Cap",
      "source": "PaB",
      "weight": 4
    },
    {
      "name": "Mindguard Crown",
      "source": "PaB",
      "weight": 4
    },
    {
      "name": "Mistral Mantle",
      "source": "BGG",
      "weight": 4
    },
    {
      "name": "Nimbus Coronet",
      "source": "BGG",
      "weight": 4
    },
    {
      "name": "Peregrine Mask",
      "source": "GGR",
      "weight": 4
    },
    {
      "name": "Robe of Scintillating Colors",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Robe of Stars",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Skull Helm",
      "source": "BMT",
      "weight": 4
    },
    {
      "name": "Wakened Scaled Ornament of [Dragon-Breath]",
      "source": "FTD",
      "weight": 4
    },
    {
      "name": "Watchful Helm",
      "source": "CM",
      "weight": 4
    },
    {
      "name": "Wyrmreaver Gauntlets",
      "source": "BGG",
      "weight": 4
    }
  ],
  "Absorbing-H": [
    {
      "name": "Acid Absorbing Green",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Cold Absorbing Blue",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Fire Absorbing Red",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Force Absorbing White",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Lightning Absorbing Yellow",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Necrotic Absorbing Black",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Poison Absorbing Violet",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Psychic Absorbing Silver",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Radiant Absorbing Gold",
      "source": "TCE",
      "weight": 1
    },
    {
      "name": "Thunder Absorbing Orange",
      "source": "TCE",
      "weight": 1
    }
  ],
  "Giant-H": [
    {
      "name": "Frost",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Stone",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Armor-H": [
    {
      "name": "[Armor], +2",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "[Dragon-H] Dragon Scale Mail",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "[Heavy-Armor] of Safeguarding",
      "source": "BGG",
      "weight": 2
    },
    {
      "name": "[Shields-H]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Antimagic [Armor]",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Clockwork [Heavy-Armor]",
      "source": "BMT",
      "weight": 2
    },
    {
      "name": "Last Stand [Armor]",
      "source": "EGW",
      "weight": 2
    },
    {
      "name": "Living [Armor]",
      "source": "ERLW",
      "weight": 2
    },
    {
      "name": "Dwarven Plate",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Hunter's Coat",
      "source": "EGW",
      "weight": 1
    }
  ],
  "Shields-H": [
    {
      "name": "Shield, +3",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Animated Shield",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Sapphire Buckler",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Shield of the Uven Rune",
      "source": "WDMM",
      "weight": 1
    },
    {
      "name": "Spellguard Shield",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Dragon-H": [
    {
      "name": "Black",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Blue",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Brass",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Bronze",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Copper",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Gold",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Green",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Red",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Silver",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "White",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Arms-H": [
    {
      "name": "[Weapons], +3",
      "source": "DMG",
      "weight": 10
    },
    {
      "name": "[Bows] of Melodies",
      "source": "BMT",
      "weight": 6
    },
    {
      "name": "[Weapons] of Throne's Command",
      "source": "BMT",
      "weight": 6
    },
    {
      "name": "Wakened Dragon's Wrath [Dragon-Breath] [Weapons]",
      "source": "FTD",
      "weight": 6
    },
    {
      "name": "Wraps of Unarmed Prowess, +3",
      "source": "BMT",
      "weight": 6
    },
    {
      "name": "[Swords] of Sharpness",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Baleful Talon",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Bloodaxe",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Bloodshed [Swords]",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Corecut Dagger",
      "source": "TDCS",
      "weight": 3
    },
    {
      "name": "Dancing [Swords]",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Duskcrusher",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Dwarven Thrower",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Dyrrn's Tentacle Whip",
      "source": "ERLW",
      "weight": 3
    },
    {
      "name": "Elven Thrower",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Fate Cutter Shears",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Fool's Blade [Swords]",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Forcebreaker [Martial-Melee]",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Hammer of Runic Focus",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Nine Lives Stealer [Swords]",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Oathbow",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Scimitar of Speed",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Steel",
      "source": "WBtW",
      "weight": 3
    },
    {
      "name": "Stonemaker War Pick",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Sword of the Paruns",
      "source": "GGR",
      "weight": 3
    },
    {
      "name": "Tidecaller Trident",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Tinkertop Boltblaster 1000",
      "source": "TDCS",
      "weight": 3
    }
  ],
  "Jewelry-H": [
    {
      "name": "[Ioun-Stone-I]",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Amethyst Lodestone",
      "source": "FTD",
      "weight": 2
    },
    {
      "name": "Amulet of the Black Skull",
      "source": "ToA",
      "weight": 2
    },
    {
      "name": "Ring of Amity",
      "source": "BGG",
      "weight": 2
    },
    {
      "name": "Ring of Shooting Stars",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Sanctum Amulet",
      "source": "BGG",
      "weight": 2
    },
    {
      "name": "Amulet of the Planes",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ring of Regeneration",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Ring of Telekinesis",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Sage's Bear Signet",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Sage's Hart Signet",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Sage's Lion Signet",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Sage's Wolf Signet",
      "source": "BMT",
      "weight": 1
    }
  ],
  "Ioun-Stone-I": [
    {
      "name": "Ioun Stone of Greater Absorption",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Ioun Stone of Mastery",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Ioun Stone of Regeneration",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Misc-H": [
    {
      "name": "[Stat-Books-H]",
      "source": "DMG",
      "weight": 24
    },
    {
      "name": "[Candle-H] Candle of Invocation",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Bobbing Lily Pad",
      "source": "WBtW",
      "weight": 3
    },
    {
      "name": "Bronze Horn of Valhalla",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Carpet of Flying",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Cauldron of Rebirth",
      "source": "TCE",
      "weight": 3
    },
    {
      "name": "Constantori's Portrait",
      "source": "KGV",
      "weight": 3
    },
    {
      "name": "Crystal Ball",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Deck of Dimensions",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Deck of Wild Cards",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Efreeti Bottle",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Ingot of the Skold Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Kyrzin's Ooze",
      "source": "ERLW",
      "weight": 3
    },
    {
      "name": "Manual of Golems",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Mirror of Life Trapping",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Mirror of Reflected Pasts",
      "source": "DL",
      "weight": 3
    },
    {
      "name": "Orb of the Veil",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Pennant of the Vind Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Prehistoric Figurine of Wondrous Power, Carnelian Triceratops",
      "source": "BGG",
      "weight": 3
    },
    {
      "name": "Shard of the Ise Rune",
      "source": "SKT",
      "weight": 3
    },
    {
      "name": "Spell Bottle",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Ventilating Lungs",
      "source": "ERLW",
      "weight": 3
    },
    {
      "name": "Wakened Dragon Vessel",
      "source": "FTD",
      "weight": 3
    },
    {
      "name": "Figurine of Wondrous Power, Obsidian Steed",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Rod of Absorption",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Rod of Alertness",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Rod of Security",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Wand of Polymorph",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Stat-Books-H": [
    {
      "name": "Manual of Gainful Exercise",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Manual of Quickness of Action",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Manual of Bodily Health",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Tome of Clear Thought",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Tome of Understanding",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Tome of Leadership and Influence",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Candle-H": [
    {
      "name": "Chaotic Evil",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Chaotic Neutral",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Chaotic Good",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Neutral Evil",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Neutral",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Neutral Good",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Lawful Evil",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Lawful Neutral",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Lawful Good",
      "source": "DMG",
      "weight": 3
    }
  ],
  "Spellcaster-H": [
    {
      "name": "All-Purpose Tool, +3",
      "source": "TCE",
      "weight": 10
    },
    {
      "name": "Moon Sickle, +3",
      "source": "TCE",
      "weight": 10
    },
    {
      "name": "Amulet of the Devout, +3",
      "source": "TCE",
      "weight": 7
    },
    {
      "name": "Bloodwell Vial, +3",
      "source": "TCE",
      "weight": 7
    },
    {
      "name": "Rhythm-Maker's Drum, +3",
      "source": "TCE",
      "weight": 7
    },
    {
      "name": "Rod of the Pact Keeper, +3",
      "source": "DMG",
      "weight": 7
    },
    {
      "name": "Arcane Grimoire, +3",
      "source": "TCE",
      "weight": 4
    },
    {
      "name": "Blast Scepter",
      "source": "WDMM",
      "weight": 3
    },
    {
      "name": "Crystalline Chronicle",
      "source": "TCE",
      "weight": 3
    },
    {
      "name": "Eldritch Staff",
      "source": "WBtW",
      "weight": 3
    },
    {
      "name": "Fate Dealer's Deck, +2",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Instrument of the Bards (Anstruth Harp)",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Rod of Hellish Flames",
      "source": "BMT",
      "weight": 3
    },
    {
      "name": "Staff of Dunamancy",
      "source": "EGW",
      "weight": 3
    },
    {
      "name": "Staff of Fate",
      "source": "CM",
      "weight": 3
    },
    {
      "name": "Staff of Fire",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Staff of Frost",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Staff of Power",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Staff of Striking",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Staff of Thunder and Lightning",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Voyager Staff",
      "source": "GGR",
      "weight": 3
    },
    {
      "name": "Wakened [FTD-Dragons]-Dragon-Touched Focus",
      "source": "FTD",
      "weight": 3
    },
    {
      "name": "Wand of the War Mage, +3",
      "source": "DMG",
      "weight": 3
    }
  ],
  "Consumables-E": [
    {
      "name": "Universal Solvent",
      "source": "DMG",
      "weight": 8
    },
    {
      "name": "Sovereign Glue",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Potions-E": [
    {
      "name": "Potion of Storm Giant Strength",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Potion of Supreme Healing",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Potion of [All-Dragons] Dragon's Majesty",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Potion of Giant Size",
      "source": "SKT",
      "weight": 1
    }
  ],
  "Spells-E": [
    {
      "name": "Spell Scroll ([Spells-Level-8])",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Spell Scroll ([Spells-Level-9])",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-8])",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Spellwrought Tattoo ([Spells-Level-9])",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Ammunition-E": [
    {
      "name": "[Ammunition] of Slaying",
      "source": "DMG",
      "weight": 6
    }
  ],
  "Apparel-I": [
    {
      "name": "Belt of Cloud Giant Strength",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Blood Fury Tattoo",
      "source": "TCE",
      "weight": 2
    },
    {
      "name": "Platinum Scarf",
      "source": "FTD",
      "weight": 2
    },
    {
      "name": "Ascendant Scaled Ornament of [Dragon-Breath]",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Belashyrra's Beholder Crown",
      "source": "ERLW",
      "weight": 1
    },
    {
      "name": "Belt of Storm Giant Strength",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Cloak of Invisibility",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Gloves of Soul Catching",
      "source": "CM",
      "weight": 1
    },
    {
      "name": "Robe of the Archmagi",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Armor-I": [
    {
      "name": "[Armor], +3",
      "source": "DMG",
      "weight": 6
    },
    {
      "name": "Efreeti Chain Mail",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Euryale's Aegis",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Plate Armor of Etherealness",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Plate Armor of Invulnerability",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Shield of the Blazing Dreadnought",
      "source": "BGG",
      "weight": 1
    },
    {
      "name": "Stonebreaker's Breastplate",
      "source": "BGG",
      "weight": 1
    }
  ],
  "Arms-I": [
    {
      "name": "Ascendant [Dragon-Breath] Dragon's Wrath [Weapons]",
      "source": "FTD",
      "weight": 2
    },
    {
      "name": "Defender [Swords]",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Longbow of the Healing Hearth",
      "source": "BGG",
      "weight": 2
    },
    {
      "name": "Reaper's Scream",
      "source": "BGG",
      "weight": 2
    },
    {
      "name": "Rod of Lordly Might",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Sword of Answering ([Answering-I])",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "[Swords] of the Planes",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Flail of Tiamat",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Hammer of Thunderbolts",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Holy Avenger [Swords]",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Luck Blade [Swords]",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Rakdos Riteknife",
      "source": "GGR",
      "weight": 1
    },
    {
      "name": "Topaz Annihilator",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Vorpal [Swords]",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Answering-I": [
    {
      "name": "Answerer, CG, Emerald",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Retorter, LG, Aquamarine",
      "source": "DMG",
      "weight": 3
    },
    {
      "name": "Back Talker, CE, Jet",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Concluder, LN, Amethyst",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Last Quip, CN, Tourmaline",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Rebutter, NG, Topaz",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Replier, N, Peridot",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Scather, LE, Garnet",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Squelcher, NE, Spinel",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Sentient-I": [
    {
      "name": "Moonblade",
      "source": "DMG",
      "weight": 10
    },
    {
      "name": "Azuredge",
      "source": "WDH",
      "weight": 9
    },
    {
      "name": "Blackrazor",
      "source": "DMG",
      "weight": 9
    },
    {
      "name": "Dawnbringer",
      "source": "OotA",
      "weight": 9
    },
    {
      "name": "Graz'tchar, the Decadent End",
      "source": "TDCSR",
      "weight": 9
    },
    {
      "name": "Hazirawn",
      "source": "ToD",
      "weight": 9
    },
    {
      "name": "Orc-Splitter",
      "source": "PotA",
      "weight": 9
    },
    {
      "name": "Snicker-Snack",
      "source": "WBtW",
      "weight": 9
    },
    {
      "name": "Wave",
      "source": "DMG",
      "weight": 9
    },
    {
      "name": "Waythe",
      "source": "TYP",
      "weight": 9
    },
    {
      "name": "Whelm",
      "source": "DMG",
      "weight": 9
    }
  ],
  "Jewelry-I": [
    {
      "name": "Shard Solitaire ([Shard-I])",
      "source": "KGV",
      "weight": 4
    },
    {
      "name": "Ring of [Elemental-I] Elemental Command",
      "source": "DMG",
      "weight": 4
    },
    {
      "name": "Ring of Djinni Summoning",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Ring of Invisibility",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Ring of Spell Turning",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Scarab of Protection",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Ring of Three Wishes",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Talisman of Pure Good",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Talisman of the Sphere",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Talisman of Ultimate Evil",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Shard-I": [
    {
      "name": "Black Sapphire",
      "source": "KGV",
      "weight": 2
    },
    {
      "name": "Diamond",
      "source": "KGV",
      "weight": 2
    },
    {
      "name": "Jacinth",
      "source": "KGV",
      "weight": 2
    },
    {
      "name": "Rainbow Pearl",
      "source": "KGV",
      "weight": 2
    },
    {
      "name": "Ruby",
      "source": "KGV",
      "weight": 2
    }
  ],
  "Elemental-I": [
    {
      "name": "Air",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Earth",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Fire",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Water",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Misc-I": [
    {
      "name": "Crystal Ball of [Crystal-Ball-I]",
      "source": "",
      "weight": 2
    },
    {
      "name": "Ascendant Dragon Vessel",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Cubic Gate",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Deck of Many More Things",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Deck of Many Things",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Gold Canary Figurine of Wondrous Power",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Harp of Gilded Plenty",
      "source": "BGG",
      "weight": 1
    },
    {
      "name": "Iron Flask",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Iron Horn of Valhalla",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Nether Scroll of Azumar",
      "source": "CM",
      "weight": 1
    },
    {
      "name": "Nightfall Pearl",
      "source": "EGW",
      "weight": 1
    },
    {
      "name": "Prehistoric Figurine of Wondrous Power, Jasper Tyrannosaurus Rex",
      "source": "BGG",
      "weight": 1
    },
    {
      "name": "Rod of Resurrection",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Scroll of Tarrasque Summoning",
      "source": "IDRotF",
      "weight": 1
    },
    {
      "name": "Scroll of the Comet",
      "source": "IDRotF",
      "weight": 1
    },
    {
      "name": "Sphere of Annihilation",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Spindle of Fate",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Telescopic Transporter",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Well of Many Worlds",
      "source": "DMG",
      "weight": 1
    }
  ],
  "Crystal-Ball-I": [
    {
      "name": "Mind Reading",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "Telepathy",
      "source": "DMG",
      "weight": 2
    },
    {
      "name": "True Seeing",
      "source": "DMG",
      "weight": 2
    }
  ],
  "Spellcaster-I": [
    {
      "name": "Ascendant Dragon-Touched Focus",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Fate Dealer's Deck, +3",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Instrument of the Bards (Ollahm Harp)",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Jester's Mask",
      "source": "BMT",
      "weight": 1
    },
    {
      "name": "Orb of Skoraeus",
      "source": "BGG",
      "weight": 1
    },
    {
      "name": "Ruby Weave Gem",
      "source": "FTD",
      "weight": 1
    },
    {
      "name": "Staff of the Magi",
      "source": "DMG",
      "weight": 1
    },
    {
      "name": "Tome of the Stilled Tongue",
      "source": "DMG",
      "weight": 1
    }
  ]
};
