// Auto-generated by scripts/extract-data.ts — do not edit

export const SOURCEBOOKS = [
  {
    "name": "Dungeon Master's Guide",
    "acronym": "DMG"
  },
  {
    "name": "Xanathar's Guide to Everything",
    "acronym": "XGE"
  },
  {
    "name": "Tasha's Cauldron of Everything",
    "acronym": "TCE"
  },
  {
    "name": "Fizban's Treasury of Dragons",
    "acronym": "FTD"
  },
  {
    "name": "Bigby Presents: Glory of the Giants",
    "acronym": "BGG"
  },
  {
    "name": "Astral Adeventurer's Guide",
    "acronym": "AAG"
  },
  {
    "name": "Strixhaven: Curriculum of Chaos",
    "acronym": "SCC"
  },
  {
    "name": "Eberron: Rising from the Last War",
    "acronym": "ERLW"
  },
  {
    "name": "Explorer's Guide to Wildemount",
    "acronym": "EGW"
  },
  {
    "name": "Tal'Dorei Campaign Setting",
    "acronym": "TDCS"
  },
  {
    "name": "Mythic Odesseys of Theros",
    "acronym": "MOT"
  },
  {
    "name": "Guildmaster's Guide to Ravnica",
    "acronym": "GGR"
  },
  {
    "name": "Tyranny of Dragons",
    "acronym": "ToD"
  },
  {
    "name": "Waterdeep: Dragon Heist",
    "acronym": "WDH"
  },
  {
    "name": "Waterdeep: Dungeon of the Mad Mage",
    "acronym": "WDMM"
  },
  {
    "name": "Icewind Dale: Rime of the Frostmaiden",
    "acronym": "IWD"
  },
  {
    "name": "Wild Beyond the Witchlight",
    "acronym": "WBtW"
  },
  {
    "name": "Tales from the Yawning Portal",
    "acronym": "TYP"
  },
  {
    "name": "Storm King's Thunder",
    "acronym": "SKT"
  },
  {
    "name": "Princes of the Apocalypse",
    "acronym": "PotA"
  },
  {
    "name": "Lost Mine of Phandelver",
    "acronym": "LMoP"
  },
  {
    "name": "Phandelver and Below",
    "acronym": "PaB"
  },
  {
    "name": "Ghosts of Saltmarsh",
    "acronym": "GoS"
  },
  {
    "name": "Tomb of Annihilation",
    "acronym": "ToA"
  },
  {
    "name": "Candlekeep Mysteries",
    "acronym": "CM"
  },
  {
    "name": "Call of the Netherdeep",
    "acronym": "CotN"
  },
  {
    "name": "Out of the Abyss",
    "acronym": "OotA"
  },
  {
    "name": "Book of Many Things",
    "acronym": "BMT"
  },
  {
    "name": "Exploring Eberron",
    "acronym": "ExE"
  }
];
