// Auto-generated by scripts/extract-data.ts — do not edit

export const SPELL_TABLES = [
  {
    "name": "Spells-Cantrip",
    "entries": [
      {
        "name": "Acid Splash",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blade Ward",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Booming Blade",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Chill Touch",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Control Flames",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Create Bonfire",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Dancing Lights",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Druidcraft",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Eldritch Blast",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Fire Bolt",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Friends",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Frostbite",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Green-Flame Blade",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Guidance",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Gust",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Infestation",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Light",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Lightning Lure",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Mage Hand",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Magic Stone",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Mending",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Message",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mind Sliver",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Minor Illusion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mold Earth",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Poison Spray",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Prestidigitation",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Primal Savagery",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Produce Flame",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Ray of Frost",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Resistance",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sacred Flame",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sapping Sting",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Shape Water",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Shillelagh",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Shocking Grasp",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Spare the Dying",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sword Burst",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Thaumaturgy",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Thorn Whip",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Thunderclap",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Toll the Dead",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "True Strike",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Vicious Mockery",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Word of Radiance",
        "source": "XGE",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-1",
    "entries": [
      {
        "name": "Absorb Elements",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Alarm",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Animal Friendship",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Armor of Agathys",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Arms of Hadar",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Bane",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Beast Bond",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Bless",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Burning Hands",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Catapult",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Cause Fear",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Ceremony",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Chaos Bolt",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Charm Person",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Chromatic Orb",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Color Spray",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Command",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Compelled Duel",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Comprehend Languages",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Create or Destroy Water",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Cure Wounds",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Detect Evil and Good",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Detect Magic",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Detect Poison and Disease",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Disguise Self",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dissonant Whispers",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Divine Favor",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Earth Tremor",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Ensnaring Strike",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Entangle",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Expeditious Retreat",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Faerie Fire",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "False Life",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Feather Fall",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Find Familiar",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Fog Cloud",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Frost Fingers",
        "source": "IWD",
        "weight": 1
      },
      {
        "name": "Gift of Alacrity",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Goodberry",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Grease",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Guiding Bolt",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hail of Thorns",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Healing Word",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hellish Rebuke",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Heroism",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hex",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hunter's Mark",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Ice Knife",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Identify",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Illusory Script",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Inflict Wounds",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Jump",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Longstrider",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mage Armor",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Magic Missile",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Magnify Gravity",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Protection from Evil and Good",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Purify Food and Drink",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Ray of Sickness",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sanctuary",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Searing Smite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Shield",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Shield of Faith",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Silent Image",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sleep",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Snare",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Speak with Animals",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Tasha's Caustic Brew",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Tasha's Hideous Laughter",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Tenser's Floating Disk",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Thunderous Smite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Thunderwave",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Unseen Servant",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Witch Bolt",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wrathful Smite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Zephyr Strike",
        "source": "XGE",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-2",
    "entries": [
      {
        "name": "Aganazzar's Scorcher",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Aid",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Air Bubble",
        "source": "AAG",
        "weight": 1
      },
      {
        "name": "Alter Self",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Animal Messenger",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Arcane Lock",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Augury",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Barkskin",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Beast Sense",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blindness/Deafness",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blur",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Borrowed Knowledge",
        "source": "SCC",
        "weight": 1
      },
      {
        "name": "Branding Smite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Calm Emotions",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Cloud of Daggers",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Continual Flame",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Cordon of Arrows",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Crown of Madness",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Darkness",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Darkvision",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Detect Thoughts",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dragon's Breath",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Dust Devil",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Earthbind",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Enhance Ability",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Enlarge/Reduce",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Enthrall",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Find Steed",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Find Traps",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Flame Blade",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Flaming Sphere",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Fortune's Favor",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Gentle Repose",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Gust of Wind",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Healing Spirit",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Heat Metal",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hold Person",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Immovable Object",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Invisibility",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Kinetic Jaunt",
        "source": "SCC",
        "weight": 1
      },
      {
        "name": "Knock",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Lesser Restoration",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Levitate",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Locate Animals or Plants",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Locate Object",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Magic Mouth",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Magic Weapon",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Maximilian's Earthen Grasp",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Melf's Acid Arrow",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mind Spike",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Mirror Image",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Misty Step",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Moonbeam",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Nathair's Mischief",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Nystul's Magic Aura",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Pass without Trace",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Phantasmal Force",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Prayer of Healing",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Protection from Poison",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Pyrotechnics",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Ray of Enfeeblement",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Rime's Binding Ice",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Rope Trick",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Scorching Ray",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "See Invisibility",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Shadow Blade",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Shatter",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Silence",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Skywrite",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Snilloc's Snowball Swarm",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Spider Climb",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Spike Growth",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Spiritual Weapon",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Spray of Cards",
        "source": "BMT",
        "weight": 1
      },
      {
        "name": "Suggestion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Summon Beast",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Tasha's Mind Whip",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Vortex Warp",
        "source": "SCC",
        "weight": 1
      },
      {
        "name": "Warding Bond",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Warding Wind",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Web",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wither and Bloom",
        "source": "SCC",
        "weight": 1
      },
      {
        "name": "Wristpocket",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Zone of Truth",
        "source": "PHB",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-3",
    "entries": [
      {
        "name": "Animate Dead",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Antagonize",
        "source": "BMT",
        "weight": 1
      },
      {
        "name": "Ashardalon's Stride",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Aura of Vitality",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Beacon of Hope",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Bestow Curse",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blinding Smite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blink",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Call Lightning",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Catnap",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Clairvoyance",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Conjure Animals",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Conjure Barrage",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Create Food and Water",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Crusader's Mantle",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Daylight",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dispel Magic",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Elemental Weapon",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Enemies Abound",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Erupting Earth",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Fear",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Feign Death",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Fireball",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Flame Arrows",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Fly",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Freedom of the Waves",
        "source": "TDCS",
        "weight": 1
      },
      {
        "name": "Gaseous Form",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Glyph of Warding",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Haste",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hunger of Hadar",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hypnotic Pattern",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Intellect Fortress",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Leomund's Tiny Hut",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Life Transference",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Lightning Arrow",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Lightning Bolt",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Magic Circle",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Major Image",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mass Healing Word",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Meld into Stone",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Melf's Minute Meteors",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Nondetection",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Phantom Steed",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Plant Growth",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Protection from Energy",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Pulse Wave",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Remove Curse",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Revivify",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sending",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sleet Storm",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Slow",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Speak with Dead",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Speak with Plants",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Spirit Guardians",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Spirit Shroud",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Stinking Cloud",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Summon Fey",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Summon Lesser Demons",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Summon Shadowspawn",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Summon Undead",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Thunder Step",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Tidal Wave",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Tiny Servant",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Tongues",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Vampiric Touch",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wall of Sand",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Wall of Water",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Water Breathing",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Water Walk",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wind Wall",
        "source": "PHB",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-4",
    "entries": [
      {
        "name": "Arcane Eye",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Aura of Life",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Aura of Purity",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Banishment",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blight",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Charm Monster",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Compulsion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Confusion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Conjure Minor Elementals",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Conjure Woodland Beings",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Control Water",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Death Ward",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dimension Door",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Divination",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dominate Beast",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Elemental Bane",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Evard's Black Tentacles",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Fabricate",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Find Greater Steed",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Fire Shield",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Freedom of Movement",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Giant Insect",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Grasping Vine",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Gravity Sinkhole",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Greater Invisibility",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Guardian of Faith",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Guardian of Nature",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Hallucinatory Terrain",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Ice Storm",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Leomund's Secret Chest",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Locate Creature",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mordenkainen's Faithful Hound",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mordenkainen's Private Sanctum",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Otiluke's Resilient Sphere",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Phantasmal Killer",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Polymorph",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Raulothim's Psychic Lance",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Shadow of Moil",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Sickening Radiance",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Spirit of Death",
        "source": "BMT",
        "weight": 1
      },
      {
        "name": "Staggering Smite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Stone Shape",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Stoneskin",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Storm Sphere",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Summon Aberration",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Summon Construct",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Summon Elemental",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Summon Greater Demon",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Vitriolic Sphere",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Wall of Fire",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Watery Sphere",
        "source": "XGE",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-5",
    "entries": [
      {
        "name": "Animate Objects",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Antilife Shell",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Awaken",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Banishing Smite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Bigby's Hand",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Circle of Power",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Cloudkill",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Commune",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Commune with Nature",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Cone of Cold",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Conjure Elemental",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Conjure Volley",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Contact Other Plane",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Contagion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Control Winds",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Creation",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Danse Macabre",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Dawn",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Destructive Wave",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dispel Evil and Good",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dominate Person",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dream",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Enervation",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Far Step",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Flame Strike",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Freedom of the Winds",
        "source": "TDCS",
        "weight": 1
      },
      {
        "name": "Geas",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Greater Restoration",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hallow",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Hold Monster",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Holy Weapon",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Immolation",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Infernal Calling",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Insect Plague",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Legend Lore",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Maelstrom",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Mass Cure Wounds",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mislead",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Modify Memory",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Negative Energy Flood",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Passwall",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Planar Binding",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Raise Dead",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Rary's Telepathic Bond",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Reincarnate",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Scrying",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Seeming",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Skill Empowerment",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Steel Wind Strike",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Summon Celestial",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Summon Draconic Spirit",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Swift Quiver",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Synaptic Static",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Telekinesis",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Teleportation Circle",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Temporal Shunt",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Transmute Rock",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Tree Stride",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wall of Force",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wall of Light",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Wall of Stone",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wrath of Nature",
        "source": "XGE",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-6",
    "entries": [
      {
        "name": "Arcane Gate",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blade Barrier",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Bones of the Earth",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Chain Lightning",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Circle of Death",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Conjure Fey",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Contingency",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Create Homunculus",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Create Undead",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Disintegrate",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Drawmij's Instant Summons",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Druid Grove",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Eyebite",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Find the Path",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Fizban's Platinum Shield",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Flesh to Stone",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Forbiddance",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Globe of Invulnerability",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Gravity Fissure",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Guards and Wards",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Harm",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Heal",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Heroes' Feast",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Investiture of Flame",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Investiture of Ice",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Investiture of Stone",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Investiture of Wind",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Magic Jar",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mass Suggestion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mental Prison",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Move Earth",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Otiluke's Freezing Sphere",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Otto's Irresistible Dance",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Planar Ally",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Primordial Ward",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Programmed Illusion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Scatter",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Soul Cage",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Summon Fiend",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Sunbeam",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Tasha's Otherworldly Guise",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Tenser's Transformation",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Transport via Plants",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "True Seeing",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wall of Ice",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wall of Thorns",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wind Walk",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Word of Recall",
        "source": "PHB",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-7",
    "entries": [
      {
        "name": "Conjure Celestial",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Create Magen",
        "source": "IWD",
        "weight": 1
      },
      {
        "name": "Crown of Stars",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Delayed Blast Fireball",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Divine Word",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Draconic Transformation",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Dream of the Blue Veil",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Etherealness",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Finger of Death",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Fire Storm",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Forcecage",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mirage Arcane",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mordenkainen's Magnificent Mansion",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mordenkainen's Sword",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Plane Shift",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Power Word Pain",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Prismatic Spray",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Project Image",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Regenerate",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Resurrection",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Reverse Gravity",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Sequester",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Simulacrum",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Symbol",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Teleport",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Temple of the Gods",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Tether Essence",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Whirlwind",
        "source": "XGE",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-8",
    "entries": [
      {
        "name": "Abi-Dalzim's Horrid Wilting",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Animal Shapes",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Antimagic Field",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Antipathy/Sympathy",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Clone",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Control Weather",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dark Star",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Demiplane",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Dominate Monster",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Earthquake",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Feeblemind",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Glibness",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Holy Aura",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Illusory Dragon",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Incendiary Cloud",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Maddening Darkness",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Maze",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mighty Fortress",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Mind Blank",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Power Word Stun",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Reality Break",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Sunburst",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Telepathy",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Tsunami",
        "source": "PHB",
        "weight": 1
      }
    ]
  },
  {
    "name": "Spells-Level-9",
    "entries": [
      {
        "name": "Astral Projection",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Blade of Disaster",
        "source": "TCE",
        "weight": 1
      },
      {
        "name": "Foresight",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Gate",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Imprisonment",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Invulnerability",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Mass Heal",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Mass Polymorph",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Meteor Swarm",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Power Word Heal",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Power Word Kill",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Prismatic Wall",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Psychic Scream",
        "source": "XGE",
        "weight": 1
      },
      {
        "name": "Ravenous Void",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Shapechange",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Storm of Vengeance",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Time Ravage",
        "source": "EGW",
        "weight": 1
      },
      {
        "name": "Time Stop",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "True Polymorph",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "True Resurrection",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Weird",
        "source": "PHB",
        "weight": 1
      },
      {
        "name": "Wish",
        "source": "PHB",
        "weight": 1
      }
    ]
  }
];
