// Auto-generated by scripts/extract-data.ts — do not edit

export const SUPPLEMENTAL_TABLES = [
  {
    "name": "Armor",
    "entries": [
      {
        "name": "[Light-Armor]",
        "source": "",
        "weight": 3
      },
      {
        "name": "[Medium-Armor]",
        "source": "",
        "weight": 3
      },
      {
        "name": "[Heavy-Armor]",
        "source": "",
        "weight": 2
      }
    ]
  },
  {
    "name": "Light-Armor",
    "entries": [
      {
        "name": "Padded Gambeson",
        "source": "",
        "weight": 1
      },
      {
        "name": "Leather Armor",
        "source": "",
        "weight": 5
      },
      {
        "name": "Studded Leather Armor",
        "source": "",
        "weight": 2
      }
    ]
  },
  {
    "name": "Medium-Armor",
    "entries": [
      {
        "name": "Hide Armor",
        "source": "",
        "weight": 1
      },
      {
        "name": "Chain Shirt",
        "source": "",
        "weight": 3
      },
      {
        "name": "Scale Mail",
        "source": "",
        "weight": 3
      },
      {
        "name": "Breastplate",
        "source": "",
        "weight": 2
      },
      {
        "name": "Half Plate Armor",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Heavy-Armor",
    "entries": [
      {
        "name": "Ring Mail",
        "source": "",
        "weight": 1
      },
      {
        "name": "Chain Mail",
        "source": "",
        "weight": 5
      },
      {
        "name": "Splint Armor",
        "source": "",
        "weight": 3
      },
      {
        "name": "Plate Armor",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Metal-Armor",
    "entries": [
      {
        "name": "Chain Shirt",
        "source": "",
        "weight": 4
      },
      {
        "name": "Scale Mail",
        "source": "",
        "weight": 3
      },
      {
        "name": "Breastplate",
        "source": "",
        "weight": 2
      },
      {
        "name": "Half Plate",
        "source": "",
        "weight": 1
      },
      {
        "name": "Ring Mail",
        "source": "",
        "weight": 1
      },
      {
        "name": "Chain Mail",
        "source": "",
        "weight": 5
      },
      {
        "name": "Splint Armor",
        "source": "",
        "weight": 3
      },
      {
        "name": "Plate Armor",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Weapons",
    "entries": [
      {
        "name": "[Simple-Melee]",
        "source": "",
        "weight": 3
      },
      {
        "name": "[Simple-Ranged]",
        "source": "",
        "weight": 2
      },
      {
        "name": "[Martial-Melee]",
        "source": "",
        "weight": 5
      },
      {
        "name": "[Martial-Ranged]",
        "source": "",
        "weight": 2
      }
    ]
  },
  {
    "name": "Simple-Melee",
    "entries": [
      {
        "name": "Dagger",
        "source": "",
        "weight": 20
      },
      {
        "name": "Handaxe",
        "source": "",
        "weight": 12
      },
      {
        "name": "Javelin",
        "source": "",
        "weight": 12
      },
      {
        "name": "Quarterstaff",
        "source": "",
        "weight": 12
      },
      {
        "name": "Spear",
        "source": "",
        "weight": 12
      },
      {
        "name": "Club",
        "source": "",
        "weight": 8
      },
      {
        "name": "Light Hammer",
        "source": "",
        "weight": 8
      },
      {
        "name": "Mace",
        "source": "",
        "weight": 8
      },
      {
        "name": "Greatclub",
        "source": "",
        "weight": 4
      },
      {
        "name": "Sickle",
        "source": "",
        "weight": 4
      }
    ]
  },
  {
    "name": "Simple-Ranged",
    "entries": [
      {
        "name": "Light Crossbow",
        "source": "",
        "weight": 6
      },
      {
        "name": "Shortbow",
        "source": "",
        "weight": 4
      },
      {
        "name": "Dart",
        "source": "",
        "weight": 1
      },
      {
        "name": "Sling",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Martial-Melee",
    "entries": [
      {
        "name": "Longsword",
        "source": "",
        "weight": 12
      },
      {
        "name": "Shortsword",
        "source": "",
        "weight": 12
      },
      {
        "name": "Battleaxe",
        "source": "",
        "weight": 8
      },
      {
        "name": "Greatsword",
        "source": "",
        "weight": 8
      },
      {
        "name": "Greataxe",
        "source": "",
        "weight": 6
      },
      {
        "name": "Morningstar",
        "source": "",
        "weight": 6
      },
      {
        "name": "Warhammer",
        "source": "",
        "weight": 6
      },
      {
        "name": "Double-Bladed Scimitar",
        "source": "ERLW",
        "weight": 4
      },
      {
        "name": "Flail",
        "source": "",
        "weight": 4
      },
      {
        "name": "Glaive",
        "source": "",
        "weight": 4
      },
      {
        "name": "Halberd",
        "source": "",
        "weight": 4
      },
      {
        "name": "Maul",
        "source": "",
        "weight": 4
      },
      {
        "name": "Pike",
        "source": "",
        "weight": 4
      },
      {
        "name": "Rapier",
        "source": "",
        "weight": 4
      },
      {
        "name": "Scimitar",
        "source": "",
        "weight": 4
      },
      {
        "name": "Whip",
        "source": "",
        "weight": 4
      },
      {
        "name": "Lance",
        "source": "",
        "weight": 2
      },
      {
        "name": "Trident",
        "source": "",
        "weight": 2
      },
      {
        "name": "War Pick",
        "source": "",
        "weight": 2
      }
    ]
  },
  {
    "name": "Martial-Ranged",
    "entries": [
      {
        "name": "Heavy Crossbow",
        "source": "",
        "weight": 9
      },
      {
        "name": "Longbow",
        "source": "",
        "weight": 6
      },
      {
        "name": "Hand Crossbow",
        "source": "",
        "weight": 3
      },
      {
        "name": "Blowgun",
        "source": "",
        "weight": 1
      },
      {
        "name": "Net",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Ammunition",
    "entries": [
      {
        "name": "Bolts",
        "source": "",
        "weight": 10
      },
      {
        "name": "Arrows",
        "source": "",
        "weight": 7
      },
      {
        "name": "Bullets",
        "source": "",
        "weight": 2
      },
      {
        "name": "Needles",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Swords",
    "entries": [
      {
        "name": "Longsword",
        "source": "",
        "weight": 4
      },
      {
        "name": "Shortsword",
        "source": "",
        "weight": 3
      },
      {
        "name": "Greatsword",
        "source": "",
        "weight": 2
      },
      {
        "name": "Double-Bladed Scimitar",
        "source": "ERLW",
        "weight": 1
      },
      {
        "name": "Rapier",
        "source": "",
        "weight": 1
      },
      {
        "name": "Scimitar",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Axes",
    "entries": [
      {
        "name": "Battleaxe",
        "source": "",
        "weight": 4
      },
      {
        "name": "Greataxe",
        "source": "",
        "weight": 2
      }
    ]
  },
  {
    "name": "Bows",
    "entries": [
      {
        "name": "Longbow",
        "source": "",
        "weight": 4
      },
      {
        "name": "Shortbow",
        "source": "",
        "weight": 3
      },
      {
        "name": "Heavy Crossbow",
        "source": "",
        "weight": 2
      },
      {
        "name": "Light Crossbow",
        "source": "",
        "weight": 2
      },
      {
        "name": "Hand Crossbow",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Ranged",
    "entries": [
      {
        "name": "[Simple-Ranged]",
        "source": "",
        "weight": 4
      },
      {
        "name": "[Martial-Ranged]",
        "source": "",
        "weight": 6
      }
    ]
  },
  {
    "name": "Dragon-Breath",
    "entries": [
      {
        "name": "[MM-Breath]",
        "source": "",
        "weight": 4
      },
      {
        "name": "[FTD-Breath]",
        "source": "",
        "weight": 2
      }
    ]
  },
  {
    "name": "MM-Breath",
    "entries": [
      {
        "name": "Fire",
        "source": "MM",
        "weight": 3
      },
      {
        "name": "Acid",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "Cold",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "Lightning",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "Poison",
        "source": "MM",
        "weight": 1
      }
    ]
  },
  {
    "name": "FTD-Breath",
    "entries": [
      {
        "name": "Force",
        "source": "FTD",
        "weight": 2
      },
      {
        "name": "Necrotic",
        "source": "FTD",
        "weight": 2
      },
      {
        "name": "Psychic",
        "source": "FTD",
        "weight": 2
      },
      {
        "name": "Radiant",
        "source": "FTD",
        "weight": 2
      },
      {
        "name": "Thunder",
        "source": "FTD",
        "weight": 2
      }
    ]
  },
  {
    "name": "FTD-Dragons",
    "entries": [
      {
        "name": "Chromatic",
        "source": "",
        "weight": 2
      },
      {
        "name": "Gem",
        "source": "",
        "weight": 2
      },
      {
        "name": "Metallic",
        "source": "",
        "weight": 2
      }
    ]
  },
  {
    "name": "All-Dragons",
    "entries": [
      {
        "name": "Red",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "Blue",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "Green",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "Black",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "White",
        "source": "MM",
        "weight": 2
      },
      {
        "name": "Gold",
        "source": "MM",
        "weight": 1
      },
      {
        "name": "Silver",
        "source": "MM",
        "weight": 1
      },
      {
        "name": "Brass",
        "source": "MM",
        "weight": 1
      },
      {
        "name": "Bronze",
        "source": "MM",
        "weight": 1
      },
      {
        "name": "Copper",
        "source": "MM",
        "weight": 1
      },
      {
        "name": "Amethyst",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Crystal",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Emerald",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Sapphire",
        "source": "FTD",
        "weight": 1
      },
      {
        "name": "Topaz",
        "source": "FTD",
        "weight": 1
      }
    ]
  },
  {
    "name": "Damage-Type",
    "entries": [
      {
        "name": "Acid",
        "source": "",
        "weight": 1
      },
      {
        "name": "Cold",
        "source": "",
        "weight": 1
      },
      {
        "name": "Fire",
        "source": "",
        "weight": 1
      },
      {
        "name": "Force",
        "source": "",
        "weight": 1
      },
      {
        "name": "Lightning",
        "source": "",
        "weight": 1
      },
      {
        "name": "Necrotic",
        "source": "",
        "weight": 1
      },
      {
        "name": "Poison",
        "source": "",
        "weight": 1
      },
      {
        "name": "Psychic",
        "source": "",
        "weight": 1
      },
      {
        "name": "Radiant",
        "source": "",
        "weight": 1
      },
      {
        "name": "Thunder",
        "source": "",
        "weight": 1
      }
    ]
  },
  {
    "name": "Tools",
    "entries": [
      {
        "name": "Cook's Utensils",
        "source": "",
        "weight": 5
      },
      {
        "name": "Disguise Kit",
        "source": "",
        "weight": 5
      },
      {
        "name": "Forgery Kit",
        "source": "",
        "weight": 5
      },
      {
        "name": "Herbalism Kit",
        "source": "",
        "weight": 5
      },
      {
        "name": "Navigator's Tools",
        "source": "",
        "weight": 5
      },
      {
        "name": "Poisoner's Kit",
        "source": "",
        "weight": 5
      },
      {
        "name": "Smith's Tools",
        "source": "",
        "weight": 5
      },
      {
        "name": "Thieves' Tools",
        "source": "",
        "weight": 5
      },
      {
        "name": "Alchemist's Supplies",
        "source": "",
        "weight": 4
      },
      {
        "name": "Brewer's Supplies",
        "source": "",
        "weight": 4
      },
      {
        "name": "Calligrapher's Supplies",
        "source": "",
        "weight": 4
      },
      {
        "name": "Carpenter's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Cartographer's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Cobbler's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Glassblower's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Jeweler's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Leatherworker's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Mason's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Painter's Supplies",
        "source": "",
        "weight": 4
      },
      {
        "name": "Potter's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Tinker's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Weaver's Tools",
        "source": "",
        "weight": 4
      },
      {
        "name": "Woodcarver's Tools",
        "source": "",
        "weight": 4
      }
    ]
  }
];
